// Code generated by mockery v2.43.0. DO NOT EDIT.

package service

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	mock "github.com/stretchr/testify/mock"

	repository "{{MODULE_NAME}}/internal/repository"
)

// MockCredentialMasterDataServiceItf is an autogenerated mock type for the CredentialMasterDataServiceItf type
type MockCredentialMasterDataServiceItf struct {
	mock.Mock
}

type MockCredentialMasterDataServiceItf_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialMasterDataServiceItf) EXPECT() *MockCredentialMasterDataServiceItf_Expecter {
	return &MockCredentialMasterDataServiceItf_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, mr, data
func (_m *MockCredentialMasterDataServiceItf) Create(ctx context.Context, mr common.MandatoryRequest, data repository.CredentialMasterData) (*repository.CredentialMasterDataRepository, error) {
	ret := _m.Called(ctx, mr, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.CredentialMasterDataRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, repository.CredentialMasterData) (*repository.CredentialMasterDataRepository, error)); ok {
		return rf(ctx, mr, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, repository.CredentialMasterData) *repository.CredentialMasterDataRepository); ok {
		r0 = rf(ctx, mr, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.CredentialMasterDataRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, repository.CredentialMasterData) error); ok {
		r1 = rf(ctx, mr, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialMasterDataServiceItf_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCredentialMasterDataServiceItf_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - data repository.CredentialMasterData
func (_e *MockCredentialMasterDataServiceItf_Expecter) Create(ctx interface{}, mr interface{}, data interface{}) *MockCredentialMasterDataServiceItf_Create_Call {
	return &MockCredentialMasterDataServiceItf_Create_Call{Call: _e.mock.On("Create", ctx, mr, data)}
}

func (_c *MockCredentialMasterDataServiceItf_Create_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, data repository.CredentialMasterData)) *MockCredentialMasterDataServiceItf_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(repository.CredentialMasterData))
	})
	return _c
}

func (_c *MockCredentialMasterDataServiceItf_Create_Call) Return(_a0 *repository.CredentialMasterDataRepository, _a1 error) *MockCredentialMasterDataServiceItf_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialMasterDataServiceItf_Create_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, repository.CredentialMasterData) (*repository.CredentialMasterDataRepository, error)) *MockCredentialMasterDataServiceItf_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function with given fields: ctx, mr, id
func (_m *MockCredentialMasterDataServiceItf) DeleteById(ctx context.Context, mr common.MandatoryRequest, id string) (*repository.CredentialMasterDataRepository, error) {
	ret := _m.Called(ctx, mr, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 *repository.CredentialMasterDataRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (*repository.CredentialMasterDataRepository, error)); ok {
		return rf(ctx, mr, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) *repository.CredentialMasterDataRepository); ok {
		r0 = rf(ctx, mr, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.CredentialMasterDataRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialMasterDataServiceItf_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockCredentialMasterDataServiceItf_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - id string
func (_e *MockCredentialMasterDataServiceItf_Expecter) DeleteById(ctx interface{}, mr interface{}, id interface{}) *MockCredentialMasterDataServiceItf_DeleteById_Call {
	return &MockCredentialMasterDataServiceItf_DeleteById_Call{Call: _e.mock.On("DeleteById", ctx, mr, id)}
}

func (_c *MockCredentialMasterDataServiceItf_DeleteById_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, id string)) *MockCredentialMasterDataServiceItf_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockCredentialMasterDataServiceItf_DeleteById_Call) Return(_a0 *repository.CredentialMasterDataRepository, _a1 error) *MockCredentialMasterDataServiceItf_DeleteById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialMasterDataServiceItf_DeleteById_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (*repository.CredentialMasterDataRepository, error)) *MockCredentialMasterDataServiceItf_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllList provides a mock function with given fields: ctx, mr
func (_m *MockCredentialMasterDataServiceItf) FindAllList(ctx context.Context, mr common.MandatoryRequest) ([]repository.CredentialMasterData, error) {
	ret := _m.Called(ctx, mr)

	if len(ret) == 0 {
		panic("no return value specified for FindAllList")
	}

	var r0 []repository.CredentialMasterData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest) ([]repository.CredentialMasterData, error)); ok {
		return rf(ctx, mr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest) []repository.CredentialMasterData); ok {
		r0 = rf(ctx, mr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.CredentialMasterData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest) error); ok {
		r1 = rf(ctx, mr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialMasterDataServiceItf_FindAllList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllList'
type MockCredentialMasterDataServiceItf_FindAllList_Call struct {
	*mock.Call
}

// FindAllList is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
func (_e *MockCredentialMasterDataServiceItf_Expecter) FindAllList(ctx interface{}, mr interface{}) *MockCredentialMasterDataServiceItf_FindAllList_Call {
	return &MockCredentialMasterDataServiceItf_FindAllList_Call{Call: _e.mock.On("FindAllList", ctx, mr)}
}

func (_c *MockCredentialMasterDataServiceItf_FindAllList_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest)) *MockCredentialMasterDataServiceItf_FindAllList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockCredentialMasterDataServiceItf_FindAllList_Call) Return(_a0 []repository.CredentialMasterData, _a1 error) *MockCredentialMasterDataServiceItf_FindAllList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialMasterDataServiceItf_FindAllList_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest) ([]repository.CredentialMasterData, error)) *MockCredentialMasterDataServiceItf_FindAllList_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllMap provides a mock function with given fields: ctx, mr
func (_m *MockCredentialMasterDataServiceItf) FindAllMap(ctx context.Context, mr common.MandatoryRequest) (map[string]repository.CredentialMasterData, error) {
	ret := _m.Called(ctx, mr)

	if len(ret) == 0 {
		panic("no return value specified for FindAllMap")
	}

	var r0 map[string]repository.CredentialMasterData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest) (map[string]repository.CredentialMasterData, error)); ok {
		return rf(ctx, mr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest) map[string]repository.CredentialMasterData); ok {
		r0 = rf(ctx, mr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]repository.CredentialMasterData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest) error); ok {
		r1 = rf(ctx, mr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialMasterDataServiceItf_FindAllMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllMap'
type MockCredentialMasterDataServiceItf_FindAllMap_Call struct {
	*mock.Call
}

// FindAllMap is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
func (_e *MockCredentialMasterDataServiceItf_Expecter) FindAllMap(ctx interface{}, mr interface{}) *MockCredentialMasterDataServiceItf_FindAllMap_Call {
	return &MockCredentialMasterDataServiceItf_FindAllMap_Call{Call: _e.mock.On("FindAllMap", ctx, mr)}
}

func (_c *MockCredentialMasterDataServiceItf_FindAllMap_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest)) *MockCredentialMasterDataServiceItf_FindAllMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockCredentialMasterDataServiceItf_FindAllMap_Call) Return(_a0 map[string]repository.CredentialMasterData, _a1 error) *MockCredentialMasterDataServiceItf_FindAllMap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialMasterDataServiceItf_FindAllMap_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest) (map[string]repository.CredentialMasterData, error)) *MockCredentialMasterDataServiceItf_FindAllMap_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function with given fields: ctx, mr, id, data
func (_m *MockCredentialMasterDataServiceItf) UpdateByID(ctx context.Context, mr common.MandatoryRequest, id string, data repository.CredentialMasterData) (*repository.CredentialMasterDataRepository, error) {
	ret := _m.Called(ctx, mr, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 *repository.CredentialMasterDataRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string, repository.CredentialMasterData) (*repository.CredentialMasterDataRepository, error)); ok {
		return rf(ctx, mr, id, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string, repository.CredentialMasterData) *repository.CredentialMasterDataRepository); ok {
		r0 = rf(ctx, mr, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.CredentialMasterDataRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string, repository.CredentialMasterData) error); ok {
		r1 = rf(ctx, mr, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialMasterDataServiceItf_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockCredentialMasterDataServiceItf_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - id string
//   - data repository.CredentialMasterData
func (_e *MockCredentialMasterDataServiceItf_Expecter) UpdateByID(ctx interface{}, mr interface{}, id interface{}, data interface{}) *MockCredentialMasterDataServiceItf_UpdateByID_Call {
	return &MockCredentialMasterDataServiceItf_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, mr, id, data)}
}

func (_c *MockCredentialMasterDataServiceItf_UpdateByID_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, id string, data repository.CredentialMasterData)) *MockCredentialMasterDataServiceItf_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string), args[3].(repository.CredentialMasterData))
	})
	return _c
}

func (_c *MockCredentialMasterDataServiceItf_UpdateByID_Call) Return(_a0 *repository.CredentialMasterDataRepository, _a1 error) *MockCredentialMasterDataServiceItf_UpdateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialMasterDataServiceItf_UpdateByID_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string, repository.CredentialMasterData) (*repository.CredentialMasterDataRepository, error)) *MockCredentialMasterDataServiceItf_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialMasterDataServiceItf creates a new instance of MockCredentialMasterDataServiceItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialMasterDataServiceItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialMasterDataServiceItf {
	mock := &MockCredentialMasterDataServiceItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
