// Code generated by mockery v2.43.0. DO NOT EDIT.

package service

import (
	mock "github.com/stretchr/testify/mock"
	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"
)

// MockKafkaPublisherServiceItf is an autogenerated mock type for the KafkaPublisherServiceItf type
type MockKafkaPublisherServiceItf struct {
	mock.Mock
}

type MockKafkaPublisherServiceItf_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKafkaPublisherServiceItf) EXPECT() *MockKafkaPublisherServiceItf_Expecter {
	return &MockKafkaPublisherServiceItf_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: mr, topic, msg, isKafkaGeneral
func (_m *MockKafkaPublisherServiceItf) Publish(mr common.MandatoryRequest, topic string, msg string, isKafkaGeneral bool) error {
	ret := _m.Called(mr, topic, msg, isKafkaGeneral)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.MandatoryRequest, string, string, bool) error); ok {
		r0 = rf(mr, topic, msg, isKafkaGeneral)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKafkaPublisherServiceItf_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockKafkaPublisherServiceItf_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - mr common.MandatoryRequest
//   - topic string
//   - msg string
//   - isKafkaGeneral bool
func (_e *MockKafkaPublisherServiceItf_Expecter) Publish(mr interface{}, topic interface{}, msg interface{}, isKafkaGeneral interface{}) *MockKafkaPublisherServiceItf_Publish_Call {
	return &MockKafkaPublisherServiceItf_Publish_Call{Call: _e.mock.On("Publish", mr, topic, msg, isKafkaGeneral)}
}

func (_c *MockKafkaPublisherServiceItf_Publish_Call) Run(run func(mr common.MandatoryRequest, topic string, msg string, isKafkaGeneral bool)) *MockKafkaPublisherServiceItf_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.MandatoryRequest), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockKafkaPublisherServiceItf_Publish_Call) Return(_a0 error) *MockKafkaPublisherServiceItf_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKafkaPublisherServiceItf_Publish_Call) RunAndReturn(run func(common.MandatoryRequest, string, string, bool) error) *MockKafkaPublisherServiceItf_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKafkaPublisherServiceItf creates a new instance of MockKafkaPublisherServiceItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaPublisherServiceItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaPublisherServiceItf {
	mock := &MockKafkaPublisherServiceItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
