// Code generated by mockery v2.43.0. DO NOT EDIT.

package service

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	enum "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/constant/enum"

	fare "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/response/fare"

	kafka "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/request/kafka"

	mock "github.com/stretchr/testify/mock"

	requestfare "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/request/fare"
)

// MockSearchServiceItf is an autogenerated mock type for the SearchServiceItf type
type MockSearchServiceItf struct {
	mock.Mock
}

type MockSearchServiceItf_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchServiceItf) EXPECT() *MockSearchServiceItf_Expecter {
	return &MockSearchServiceItf_Expecter{mock: &_m.Mock}
}

// PublishSearchResponse provides a mock function with given fields: mr, res, err
func (_m *MockSearchServiceItf) PublishSearchResponse(mr common.MandatoryRequest, res fare.FlightIntegratorSearchResponse, err error) {
	_m.Called(mr, res, err)
}

// MockSearchServiceItf_PublishSearchResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishSearchResponse'
type MockSearchServiceItf_PublishSearchResponse_Call struct {
	*mock.Call
}

// PublishSearchResponse is a helper method to define mock.On call
//   - mr common.MandatoryRequest
//   - res fare.FlightIntegratorSearchResponse
//   - err error
func (_e *MockSearchServiceItf_Expecter) PublishSearchResponse(mr interface{}, res interface{}, err interface{}) *MockSearchServiceItf_PublishSearchResponse_Call {
	return &MockSearchServiceItf_PublishSearchResponse_Call{Call: _e.mock.On("PublishSearchResponse", mr, res, err)}
}

func (_c *MockSearchServiceItf_PublishSearchResponse_Call) Run(run func(mr common.MandatoryRequest, res fare.FlightIntegratorSearchResponse, err error)) *MockSearchServiceItf_PublishSearchResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.MandatoryRequest), args[1].(fare.FlightIntegratorSearchResponse), args[2].(error))
	})
	return _c
}

func (_c *MockSearchServiceItf_PublishSearchResponse_Call) Return() *MockSearchServiceItf_PublishSearchResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSearchServiceItf_PublishSearchResponse_Call) RunAndReturn(run func(common.MandatoryRequest, fare.FlightIntegratorSearchResponse, error)) *MockSearchServiceItf_PublishSearchResponse_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAndPublish provides a mock function with given fields: ctx, mr, req, tripType, supplierMapping
func (_m *MockSearchServiceItf) SearchAndPublish(ctx context.Context, mr common.MandatoryRequest, req requestfare.IntegratorFareRequest, tripType enum.TripType, supplierMapping requestfare.SupplierMapping) (fare.FlightIntegratorSearchResponse, error) {
	ret := _m.Called(ctx, mr, req, tripType, supplierMapping)

	if len(ret) == 0 {
		panic("no return value specified for SearchAndPublish")
	}

	var r0 fare.FlightIntegratorSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, requestfare.IntegratorFareRequest, enum.TripType, requestfare.SupplierMapping) (fare.FlightIntegratorSearchResponse, error)); ok {
		return rf(ctx, mr, req, tripType, supplierMapping)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, requestfare.IntegratorFareRequest, enum.TripType, requestfare.SupplierMapping) fare.FlightIntegratorSearchResponse); ok {
		r0 = rf(ctx, mr, req, tripType, supplierMapping)
	} else {
		r0 = ret.Get(0).(fare.FlightIntegratorSearchResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, requestfare.IntegratorFareRequest, enum.TripType, requestfare.SupplierMapping) error); ok {
		r1 = rf(ctx, mr, req, tripType, supplierMapping)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchServiceItf_SearchAndPublish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAndPublish'
type MockSearchServiceItf_SearchAndPublish_Call struct {
	*mock.Call
}

// SearchAndPublish is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - req requestfare.IntegratorFareRequest
//   - tripType enum.TripType
//   - supplierMapping requestfare.SupplierMapping
func (_e *MockSearchServiceItf_Expecter) SearchAndPublish(ctx interface{}, mr interface{}, req interface{}, tripType interface{}, supplierMapping interface{}) *MockSearchServiceItf_SearchAndPublish_Call {
	return &MockSearchServiceItf_SearchAndPublish_Call{Call: _e.mock.On("SearchAndPublish", ctx, mr, req, tripType, supplierMapping)}
}

func (_c *MockSearchServiceItf_SearchAndPublish_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, req requestfare.IntegratorFareRequest, tripType enum.TripType, supplierMapping requestfare.SupplierMapping)) *MockSearchServiceItf_SearchAndPublish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(requestfare.IntegratorFareRequest), args[3].(enum.TripType), args[4].(requestfare.SupplierMapping))
	})
	return _c
}

func (_c *MockSearchServiceItf_SearchAndPublish_Call) Return(_a0 fare.FlightIntegratorSearchResponse, _a1 error) *MockSearchServiceItf_SearchAndPublish_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchServiceItf_SearchAndPublish_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, requestfare.IntegratorFareRequest, enum.TripType, requestfare.SupplierMapping) (fare.FlightIntegratorSearchResponse, error)) *MockSearchServiceItf_SearchAndPublish_Call {
	_c.Call.Return(run)
	return _c
}

// SearchKafka provides a mock function with given fields: ctx, msg
func (_m *MockSearchServiceItf) SearchKafka(ctx context.Context, msg kafka.KafkaIntegratorFareRequest) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for SearchKafka")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, kafka.KafkaIntegratorFareRequest) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSearchServiceItf_SearchKafka_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchKafka'
type MockSearchServiceItf_SearchKafka_Call struct {
	*mock.Call
}

// SearchKafka is a helper method to define mock.On call
//   - ctx context.Context
//   - msg kafka.KafkaIntegratorFareRequest
func (_e *MockSearchServiceItf_Expecter) SearchKafka(ctx interface{}, msg interface{}) *MockSearchServiceItf_SearchKafka_Call {
	return &MockSearchServiceItf_SearchKafka_Call{Call: _e.mock.On("SearchKafka", ctx, msg)}
}

func (_c *MockSearchServiceItf_SearchKafka_Call) Run(run func(ctx context.Context, msg kafka.KafkaIntegratorFareRequest)) *MockSearchServiceItf_SearchKafka_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(kafka.KafkaIntegratorFareRequest))
	})
	return _c
}

func (_c *MockSearchServiceItf_SearchKafka_Call) Return(_a0 error) *MockSearchServiceItf_SearchKafka_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSearchServiceItf_SearchKafka_Call) RunAndReturn(run func(context.Context, kafka.KafkaIntegratorFareRequest) error) *MockSearchServiceItf_SearchKafka_Call {
	_c.Call.Return(run)
	return _c
}

// SearchWithMetric provides a mock function with given fields: ctx, mr, req, tripType, supplierMapping
func (_m *MockSearchServiceItf) SearchWithMetric(ctx context.Context, mr common.MandatoryRequest, req requestfare.IntegratorFareRequest, tripType enum.TripType, supplierMapping requestfare.SupplierMapping) (fare.FlightIntegratorSearchResponse, error) {
	ret := _m.Called(ctx, mr, req, tripType, supplierMapping)

	if len(ret) == 0 {
		panic("no return value specified for SearchWithMetric")
	}

	var r0 fare.FlightIntegratorSearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, requestfare.IntegratorFareRequest, enum.TripType, requestfare.SupplierMapping) (fare.FlightIntegratorSearchResponse, error)); ok {
		return rf(ctx, mr, req, tripType, supplierMapping)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, requestfare.IntegratorFareRequest, enum.TripType, requestfare.SupplierMapping) fare.FlightIntegratorSearchResponse); ok {
		r0 = rf(ctx, mr, req, tripType, supplierMapping)
	} else {
		r0 = ret.Get(0).(fare.FlightIntegratorSearchResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, requestfare.IntegratorFareRequest, enum.TripType, requestfare.SupplierMapping) error); ok {
		r1 = rf(ctx, mr, req, tripType, supplierMapping)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchServiceItf_SearchWithMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchWithMetric'
type MockSearchServiceItf_SearchWithMetric_Call struct {
	*mock.Call
}

// SearchWithMetric is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - req requestfare.IntegratorFareRequest
//   - tripType enum.TripType
//   - supplierMapping requestfare.SupplierMapping
func (_e *MockSearchServiceItf_Expecter) SearchWithMetric(ctx interface{}, mr interface{}, req interface{}, tripType interface{}, supplierMapping interface{}) *MockSearchServiceItf_SearchWithMetric_Call {
	return &MockSearchServiceItf_SearchWithMetric_Call{Call: _e.mock.On("SearchWithMetric", ctx, mr, req, tripType, supplierMapping)}
}

func (_c *MockSearchServiceItf_SearchWithMetric_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, req requestfare.IntegratorFareRequest, tripType enum.TripType, supplierMapping requestfare.SupplierMapping)) *MockSearchServiceItf_SearchWithMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(requestfare.IntegratorFareRequest), args[3].(enum.TripType), args[4].(requestfare.SupplierMapping))
	})
	return _c
}

func (_c *MockSearchServiceItf_SearchWithMetric_Call) Return(_a0 fare.FlightIntegratorSearchResponse, _a1 error) *MockSearchServiceItf_SearchWithMetric_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchServiceItf_SearchWithMetric_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, requestfare.IntegratorFareRequest, enum.TripType, requestfare.SupplierMapping) (fare.FlightIntegratorSearchResponse, error)) *MockSearchServiceItf_SearchWithMetric_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearchServiceItf creates a new instance of MockSearchServiceItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchServiceItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchServiceItf {
	mock := &MockSearchServiceItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
