// Code generated by mockery v2.43.0. DO NOT EDIT.

package service

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	dto "{{MODULE_NAME}}/internal/shared/dto"

	entity "{{MODULE_NAME}}/internal/shared/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockCredentialServiceItf is an autogenerated mock type for the CredentialServiceItf type
type MockCredentialServiceItf struct {
	mock.Mock
}

type MockCredentialServiceItf_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialServiceItf) EXPECT() *MockCredentialServiceItf_Expecter {
	return &MockCredentialServiceItf_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, mr, data
func (_m *MockCredentialServiceItf) Create(ctx context.Context, mr common.MandatoryRequest, data entity.Credential) (entity.CredentialRepository, error) {
	ret := _m.Called(ctx, mr, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, entity.Credential) (entity.CredentialRepository, error)); ok {
		return rf(ctx, mr, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, entity.Credential) entity.CredentialRepository); ok {
		r0 = rf(ctx, mr, data)
	} else {
		r0 = ret.Get(0).(entity.CredentialRepository)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, entity.Credential) error); ok {
		r1 = rf(ctx, mr, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialServiceItf_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCredentialServiceItf_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - data entity.Credential
func (_e *MockCredentialServiceItf_Expecter) Create(ctx interface{}, mr interface{}, data interface{}) *MockCredentialServiceItf_Create_Call {
	return &MockCredentialServiceItf_Create_Call{Call: _e.mock.On("Create", ctx, mr, data)}
}

func (_c *MockCredentialServiceItf_Create_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, data entity.Credential)) *MockCredentialServiceItf_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(entity.Credential))
	})
	return _c
}

func (_c *MockCredentialServiceItf_Create_Call) Return(_a0 entity.CredentialRepository, _a1 error) *MockCredentialServiceItf_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialServiceItf_Create_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, entity.Credential) (entity.CredentialRepository, error)) *MockCredentialServiceItf_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function with given fields: ctx, mr, id
func (_m *MockCredentialServiceItf) DeleteById(ctx context.Context, mr common.MandatoryRequest, id string) (entity.CredentialRepository, error) {
	ret := _m.Called(ctx, mr, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (entity.CredentialRepository, error)); ok {
		return rf(ctx, mr, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) entity.CredentialRepository); ok {
		r0 = rf(ctx, mr, id)
	} else {
		r0 = ret.Get(0).(entity.CredentialRepository)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialServiceItf_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockCredentialServiceItf_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - id string
func (_e *MockCredentialServiceItf_Expecter) DeleteById(ctx interface{}, mr interface{}, id interface{}) *MockCredentialServiceItf_DeleteById_Call {
	return &MockCredentialServiceItf_DeleteById_Call{Call: _e.mock.On("DeleteById", ctx, mr, id)}
}

func (_c *MockCredentialServiceItf_DeleteById_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, id string)) *MockCredentialServiceItf_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockCredentialServiceItf_DeleteById_Call) Return(_a0 entity.CredentialRepository, _a1 error) *MockCredentialServiceItf_DeleteById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialServiceItf_DeleteById_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (entity.CredentialRepository, error)) *MockCredentialServiceItf_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, mr, id
func (_m *MockCredentialServiceItf) FindByID(ctx context.Context, mr common.MandatoryRequest, id string) (entity.CredentialRepository, error) {
	ret := _m.Called(ctx, mr, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (entity.CredentialRepository, error)); ok {
		return rf(ctx, mr, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) entity.CredentialRepository); ok {
		r0 = rf(ctx, mr, id)
	} else {
		r0 = ret.Get(0).(entity.CredentialRepository)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialServiceItf_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCredentialServiceItf_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - id string
func (_e *MockCredentialServiceItf_Expecter) FindByID(ctx interface{}, mr interface{}, id interface{}) *MockCredentialServiceItf_FindByID_Call {
	return &MockCredentialServiceItf_FindByID_Call{Call: _e.mock.On("FindByID", ctx, mr, id)}
}

func (_c *MockCredentialServiceItf_FindByID_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, id string)) *MockCredentialServiceItf_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockCredentialServiceItf_FindByID_Call) Return(_a0 entity.CredentialRepository, _a1 error) *MockCredentialServiceItf_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialServiceItf_FindByID_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (entity.CredentialRepository, error)) *MockCredentialServiceItf_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySupplier provides a mock function with given fields: ctx, mr, supplier
func (_m *MockCredentialServiceItf) FindBySupplier(ctx context.Context, mr common.MandatoryRequest, supplier string) (entity.CredentialRepository, error) {
	ret := _m.Called(ctx, mr, supplier)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplier")
	}

	var r0 entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (entity.CredentialRepository, error)); ok {
		return rf(ctx, mr, supplier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) entity.CredentialRepository); ok {
		r0 = rf(ctx, mr, supplier)
	} else {
		r0 = ret.Get(0).(entity.CredentialRepository)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, supplier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialServiceItf_FindBySupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplier'
type MockCredentialServiceItf_FindBySupplier_Call struct {
	*mock.Call
}

// FindBySupplier is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - supplier string
func (_e *MockCredentialServiceItf_Expecter) FindBySupplier(ctx interface{}, mr interface{}, supplier interface{}) *MockCredentialServiceItf_FindBySupplier_Call {
	return &MockCredentialServiceItf_FindBySupplier_Call{Call: _e.mock.On("FindBySupplier", ctx, mr, supplier)}
}

func (_c *MockCredentialServiceItf_FindBySupplier_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, supplier string)) *MockCredentialServiceItf_FindBySupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockCredentialServiceItf_FindBySupplier_Call) Return(_a0 entity.CredentialRepository, _a1 error) *MockCredentialServiceItf_FindBySupplier_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialServiceItf_FindBySupplier_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (entity.CredentialRepository, error)) *MockCredentialServiceItf_FindBySupplier_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySupplierInCache provides a mock function with given fields: ctx, mr, supplier
func (_m *MockCredentialServiceItf) FindBySupplierInCache(ctx context.Context, mr common.MandatoryRequest, supplier string) (entity.CredentialRepository, error) {
	ret := _m.Called(ctx, mr, supplier)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplierInCache")
	}

	var r0 entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (entity.CredentialRepository, error)); ok {
		return rf(ctx, mr, supplier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) entity.CredentialRepository); ok {
		r0 = rf(ctx, mr, supplier)
	} else {
		r0 = ret.Get(0).(entity.CredentialRepository)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, supplier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialServiceItf_FindBySupplierInCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplierInCache'
type MockCredentialServiceItf_FindBySupplierInCache_Call struct {
	*mock.Call
}

// FindBySupplierInCache is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - supplier string
func (_e *MockCredentialServiceItf_Expecter) FindBySupplierInCache(ctx interface{}, mr interface{}, supplier interface{}) *MockCredentialServiceItf_FindBySupplierInCache_Call {
	return &MockCredentialServiceItf_FindBySupplierInCache_Call{Call: _e.mock.On("FindBySupplierInCache", ctx, mr, supplier)}
}

func (_c *MockCredentialServiceItf_FindBySupplierInCache_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, supplier string)) *MockCredentialServiceItf_FindBySupplierInCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockCredentialServiceItf_FindBySupplierInCache_Call) Return(_a0 entity.CredentialRepository, _a1 error) *MockCredentialServiceItf_FindBySupplierInCache_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialServiceItf_FindBySupplierInCache_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (entity.CredentialRepository, error)) *MockCredentialServiceItf_FindBySupplierInCache_Call {
	_c.Call.Return(run)
	return _c
}

// FindWithPaginated provides a mock function with given fields: ctx, mr, cf, page, size, sort, sortDirect
func (_m *MockCredentialServiceItf) FindWithPaginated(ctx context.Context, mr common.MandatoryRequest, cf dto.CredentialFilter, page int64, size int64, sort string, sortDirect string) (CredentialPaginatedResponse, error) {
	ret := _m.Called(ctx, mr, cf, page, size, sort, sortDirect)

	if len(ret) == 0 {
		panic("no return value specified for FindWithPaginated")
	}

	var r0 CredentialPaginatedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, dto.CredentialFilter, int64, int64, string, string) (CredentialPaginatedResponse, error)); ok {
		return rf(ctx, mr, cf, page, size, sort, sortDirect)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, dto.CredentialFilter, int64, int64, string, string) CredentialPaginatedResponse); ok {
		r0 = rf(ctx, mr, cf, page, size, sort, sortDirect)
	} else {
		r0 = ret.Get(0).(CredentialPaginatedResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, dto.CredentialFilter, int64, int64, string, string) error); ok {
		r1 = rf(ctx, mr, cf, page, size, sort, sortDirect)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialServiceItf_FindWithPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWithPaginated'
type MockCredentialServiceItf_FindWithPaginated_Call struct {
	*mock.Call
}

// FindWithPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - cf dto.CredentialFilter
//   - page int64
//   - size int64
//   - sort string
//   - sortDirect string
func (_e *MockCredentialServiceItf_Expecter) FindWithPaginated(ctx interface{}, mr interface{}, cf interface{}, page interface{}, size interface{}, sort interface{}, sortDirect interface{}) *MockCredentialServiceItf_FindWithPaginated_Call {
	return &MockCredentialServiceItf_FindWithPaginated_Call{Call: _e.mock.On("FindWithPaginated", ctx, mr, cf, page, size, sort, sortDirect)}
}

func (_c *MockCredentialServiceItf_FindWithPaginated_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, cf dto.CredentialFilter, page int64, size int64, sort string, sortDirect string)) *MockCredentialServiceItf_FindWithPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(dto.CredentialFilter), args[3].(int64), args[4].(int64), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockCredentialServiceItf_FindWithPaginated_Call) Return(_a0 CredentialPaginatedResponse, _a1 error) *MockCredentialServiceItf_FindWithPaginated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialServiceItf_FindWithPaginated_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, dto.CredentialFilter, int64, int64, string, string) (CredentialPaginatedResponse, error)) *MockCredentialServiceItf_FindWithPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function with given fields: ctx, mr, id, data
func (_m *MockCredentialServiceItf) UpdateByID(ctx context.Context, mr common.MandatoryRequest, id string, data entity.Credential) (entity.CredentialRepository, error) {
	ret := _m.Called(ctx, mr, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string, entity.Credential) (entity.CredentialRepository, error)); ok {
		return rf(ctx, mr, id, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string, entity.Credential) entity.CredentialRepository); ok {
		r0 = rf(ctx, mr, id, data)
	} else {
		r0 = ret.Get(0).(entity.CredentialRepository)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string, entity.Credential) error); ok {
		r1 = rf(ctx, mr, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialServiceItf_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockCredentialServiceItf_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - id string
//   - data entity.Credential
func (_e *MockCredentialServiceItf_Expecter) UpdateByID(ctx interface{}, mr interface{}, id interface{}, data interface{}) *MockCredentialServiceItf_UpdateByID_Call {
	return &MockCredentialServiceItf_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, mr, id, data)}
}

func (_c *MockCredentialServiceItf_UpdateByID_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, id string, data entity.Credential)) *MockCredentialServiceItf_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string), args[3].(entity.Credential))
	})
	return _c
}

func (_c *MockCredentialServiceItf_UpdateByID_Call) Return(_a0 entity.CredentialRepository, _a1 error) *MockCredentialServiceItf_UpdateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialServiceItf_UpdateByID_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string, entity.Credential) (entity.CredentialRepository, error)) *MockCredentialServiceItf_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialServiceItf creates a new instance of MockCredentialServiceItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialServiceItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialServiceItf {
	mock := &MockCredentialServiceItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
