// Code generated by mockery v2.43.0. DO NOT EDIT.

package service

import (
	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"
	book "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/request/book"

	context "context"

	mock "github.com/stretchr/testify/mock"

	responsebook "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/response/book"
)

// MockBookingServiceItf is an autogenerated mock type for the BookingServiceItf type
type MockBookingServiceItf struct {
	mock.Mock
}

type MockBookingServiceItf_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBookingServiceItf) EXPECT() *MockBookingServiceItf_Expecter {
	return &MockBookingServiceItf_Expecter{mock: &_m.Mock}
}

// Booking provides a mock function with given fields: ctx, mr, integratorBookRequest
func (_m *MockBookingServiceItf) Booking(ctx context.Context, mr common.MandatoryRequest, integratorBookRequest book.IntegratorBookRequest) (responsebook.BookResponse, error) {
	ret := _m.Called(ctx, mr, integratorBookRequest)

	if len(ret) == 0 {
		panic("no return value specified for Booking")
	}

	var r0 responsebook.BookResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, book.IntegratorBookRequest) (responsebook.BookResponse, error)); ok {
		return rf(ctx, mr, integratorBookRequest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, book.IntegratorBookRequest) responsebook.BookResponse); ok {
		r0 = rf(ctx, mr, integratorBookRequest)
	} else {
		r0 = ret.Get(0).(responsebook.BookResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, book.IntegratorBookRequest) error); ok {
		r1 = rf(ctx, mr, integratorBookRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBookingServiceItf_Booking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Booking'
type MockBookingServiceItf_Booking_Call struct {
	*mock.Call
}

// Booking is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - integratorBookRequest book.IntegratorBookRequest
func (_e *MockBookingServiceItf_Expecter) Booking(ctx interface{}, mr interface{}, integratorBookRequest interface{}) *MockBookingServiceItf_Booking_Call {
	return &MockBookingServiceItf_Booking_Call{Call: _e.mock.On("Booking", ctx, mr, integratorBookRequest)}
}

func (_c *MockBookingServiceItf_Booking_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, integratorBookRequest book.IntegratorBookRequest)) *MockBookingServiceItf_Booking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(book.IntegratorBookRequest))
	})
	return _c
}

func (_c *MockBookingServiceItf_Booking_Call) Return(_a0 responsebook.BookResponse, _a1 error) *MockBookingServiceItf_Booking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBookingServiceItf_Booking_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, book.IntegratorBookRequest) (responsebook.BookResponse, error)) *MockBookingServiceItf_Booking_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBookingServiceItf creates a new instance of MockBookingServiceItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBookingServiceItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBookingServiceItf {
	mock := &MockBookingServiceItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
