// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package inbound

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/tiket/TIX-HOTEL-UTILITIES-GO/messaging"
)

// NewMockIntegratorListener creates a new instance of MockIntegratorListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIntegratorListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIntegratorListener {
	mock := &MockIntegratorListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIntegratorListener is an autogenerated mock type for the IntegratorListener type
type MockIntegratorListener struct {
	mock.Mock
}

type MockIntegratorListener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIntegratorListener) EXPECT() *MockIntegratorListener_Expecter {
	return &MockIntegratorListener_Expecter{mock: &_m.Mock}
}

// ListenToIntegratorRequest provides a mock function for the type MockIntegratorListener
func (_mock *MockIntegratorListener) ListenToIntegratorRequest(data []byte, headers []messaging.Header, n int64, n1 int64) error {
	ret := _mock.Called(data, headers, n, n1)

	if len(ret) == 0 {
		panic("no return value specified for ListenToIntegratorRequest")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, []messaging.Header, int64, int64) error); ok {
		r0 = returnFunc(data, headers, n, n1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIntegratorListener_ListenToIntegratorRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenToIntegratorRequest'
type MockIntegratorListener_ListenToIntegratorRequest_Call struct {
	*mock.Call
}

// ListenToIntegratorRequest is a helper method to define mock.On call
//   - data []byte
//   - headers []messaging.Header
//   - n int64
//   - n1 int64
func (_e *MockIntegratorListener_Expecter) ListenToIntegratorRequest(data interface{}, headers interface{}, n interface{}, n1 interface{}) *MockIntegratorListener_ListenToIntegratorRequest_Call {
	return &MockIntegratorListener_ListenToIntegratorRequest_Call{Call: _e.mock.On("ListenToIntegratorRequest", data, headers, n, n1)}
}

func (_c *MockIntegratorListener_ListenToIntegratorRequest_Call) Run(run func(data []byte, headers []messaging.Header, n int64, n1 int64)) *MockIntegratorListener_ListenToIntegratorRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 []messaging.Header
		if args[1] != nil {
			arg1 = args[1].([]messaging.Header)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIntegratorListener_ListenToIntegratorRequest_Call) Return(err error) *MockIntegratorListener_ListenToIntegratorRequest_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIntegratorListener_ListenToIntegratorRequest_Call) RunAndReturn(run func(data []byte, headers []messaging.Header, n int64, n1 int64) error) *MockIntegratorListener_ListenToIntegratorRequest_Call {
	_c.Call.Return(run)
	return _c
}
