// Code generated by mockery v2.43.0. DO NOT EDIT.

package bau

import (
	mock "github.com/stretchr/testify/mock"
	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"
)

// MockAnalyticsService is an autogenerated mock type for the AnalyticsService type
type MockAnalyticsService[T interface{}] struct {
	mock.Mock
}

type MockAnalyticsService_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsService[T]) EXPECT() *MockAnalyticsService_Expecter[T] {
	return &MockAnalyticsService_Expecter[T]{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: mr, analyticToken, err
func (_m *MockAnalyticsService[T]) Complete(mr common.MandatoryRequest, analyticToken AnalyticsTokenModifier, err error) {
	_m.Called(mr, analyticToken, err)
}

// MockAnalyticsService_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockAnalyticsService_Complete_Call[T interface{}] struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - mr common.MandatoryRequest
//   - analyticToken AnalyticsTokenModifier
//   - err error
func (_e *MockAnalyticsService_Expecter[T]) Complete(mr interface{}, analyticToken interface{}, err interface{}) *MockAnalyticsService_Complete_Call[T] {
	return &MockAnalyticsService_Complete_Call[T]{Call: _e.mock.On("Complete", mr, analyticToken, err)}
}

func (_c *MockAnalyticsService_Complete_Call[T]) Run(run func(mr common.MandatoryRequest, analyticToken AnalyticsTokenModifier, err error)) *MockAnalyticsService_Complete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.MandatoryRequest), args[1].(AnalyticsTokenModifier), args[2].(error))
	})
	return _c
}

func (_c *MockAnalyticsService_Complete_Call[T]) Return() *MockAnalyticsService_Complete_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockAnalyticsService_Complete_Call[T]) RunAndReturn(run func(common.MandatoryRequest, AnalyticsTokenModifier, error)) *MockAnalyticsService_Complete_Call[T] {
	_c.Call.Return(run)
	return _c
}

// CreateToken provides a mock function with given fields: mr, integratorRequest
func (_m *MockAnalyticsService[T]) CreateToken(mr common.MandatoryRequest, integratorRequest T) AnalyticsTokenModifier {
	ret := _m.Called(mr, integratorRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 AnalyticsTokenModifier
	if rf, ok := ret.Get(0).(func(common.MandatoryRequest, T) AnalyticsTokenModifier); ok {
		r0 = rf(mr, integratorRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(AnalyticsTokenModifier)
		}
	}

	return r0
}

// MockAnalyticsService_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockAnalyticsService_CreateToken_Call[T interface{}] struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - mr common.MandatoryRequest
//   - integratorRequest T
func (_e *MockAnalyticsService_Expecter[T]) CreateToken(mr interface{}, integratorRequest interface{}) *MockAnalyticsService_CreateToken_Call[T] {
	return &MockAnalyticsService_CreateToken_Call[T]{Call: _e.mock.On("CreateToken", mr, integratorRequest)}
}

func (_c *MockAnalyticsService_CreateToken_Call[T]) Run(run func(mr common.MandatoryRequest, integratorRequest T)) *MockAnalyticsService_CreateToken_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.MandatoryRequest), args[1].(T))
	})
	return _c
}

func (_c *MockAnalyticsService_CreateToken_Call[T]) Return(_a0 AnalyticsTokenModifier) *MockAnalyticsService_CreateToken_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnalyticsService_CreateToken_Call[T]) RunAndReturn(run func(common.MandatoryRequest, T) AnalyticsTokenModifier) *MockAnalyticsService_CreateToken_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockAnalyticsService creates a new instance of MockAnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsService[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsService[T] {
	mock := &MockAnalyticsService[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
