// Code generated by mockery v2.43.0. DO NOT EDIT.

package service

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthCheckServiceItf is an autogenerated mock type for the HealthCheckServiceItf type
type MockHealthCheckServiceItf struct {
	mock.Mock
}

type MockHealthCheckServiceItf_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthCheckServiceItf) EXPECT() *MockHealthCheckServiceItf_Expecter {
	return &MockHealthCheckServiceItf_Expecter{mock: &_m.Mock}
}

// HealthCheck provides a mock function with given fields: ctx, mr
func (_m *MockHealthCheckServiceItf) HealthCheck(ctx context.Context, mr common.MandatoryRequest) error {
	ret := _m.Called(ctx, mr)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest) error); ok {
		r0 = rf(ctx, mr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthCheckServiceItf_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockHealthCheckServiceItf_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
func (_e *MockHealthCheckServiceItf_Expecter) HealthCheck(ctx interface{}, mr interface{}) *MockHealthCheckServiceItf_HealthCheck_Call {
	return &MockHealthCheckServiceItf_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx, mr)}
}

func (_c *MockHealthCheckServiceItf_HealthCheck_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest)) *MockHealthCheckServiceItf_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockHealthCheckServiceItf_HealthCheck_Call) Return(_a0 error) *MockHealthCheckServiceItf_HealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthCheckServiceItf_HealthCheck_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest) error) *MockHealthCheckServiceItf_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthCheckServiceItf creates a new instance of MockHealthCheckServiceItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthCheckServiceItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthCheckServiceItf {
	mock := &MockHealthCheckServiceItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
