// Code generated by mockery v2.53.3. DO NOT EDIT.

package service

import (
	cancel_book "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/request/cancel-book"
	cancelbook "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/response/cancel-book"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCancelBookingService is an autogenerated mock type for the CancelBookingService type
type MockCancelBookingService struct {
	mock.Mock
}

type MockCancelBookingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCancelBookingService) EXPECT() *MockCancelBookingService_Expecter {
	return &MockCancelBookingService_Expecter{mock: &_m.Mock}
}

// CancelBooking provides a mock function with given fields: ctx, mr, req
func (_m *MockCancelBookingService) CancelBooking(ctx context.Context, mr common.MandatoryRequest, req cancel_book.IntegratorCancelBookRequest) (cancelbook.CancelBookResponse, error) {
	ret := _m.Called(ctx, mr, req)

	if len(ret) == 0 {
		panic("no return value specified for CancelBooking")
	}

	var r0 cancelbook.CancelBookResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, cancel_book.IntegratorCancelBookRequest) (cancelbook.CancelBookResponse, error)); ok {
		return rf(ctx, mr, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, cancel_book.IntegratorCancelBookRequest) cancelbook.CancelBookResponse); ok {
		r0 = rf(ctx, mr, req)
	} else {
		r0 = ret.Get(0).(cancelbook.CancelBookResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, cancel_book.IntegratorCancelBookRequest) error); ok {
		r1 = rf(ctx, mr, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCancelBookingService_CancelBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelBooking'
type MockCancelBookingService_CancelBooking_Call struct {
	*mock.Call
}

// CancelBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - req cancel_book.IntegratorCancelBookRequest
func (_e *MockCancelBookingService_Expecter) CancelBooking(ctx interface{}, mr interface{}, req interface{}) *MockCancelBookingService_CancelBooking_Call {
	return &MockCancelBookingService_CancelBooking_Call{Call: _e.mock.On("CancelBooking", ctx, mr, req)}
}

func (_c *MockCancelBookingService_CancelBooking_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, req cancel_book.IntegratorCancelBookRequest)) *MockCancelBookingService_CancelBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(cancel_book.IntegratorCancelBookRequest))
	})
	return _c
}

func (_c *MockCancelBookingService_CancelBooking_Call) Return(_a0 cancelbook.CancelBookResponse, _a1 error) *MockCancelBookingService_CancelBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCancelBookingService_CancelBooking_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, cancel_book.IntegratorCancelBookRequest) (cancelbook.CancelBookResponse, error)) *MockCancelBookingService_CancelBooking_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCancelBookingService creates a new instance of MockCancelBookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCancelBookingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCancelBookingService {
	mock := &MockCancelBookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
