// Code generated by mockery v2.43.0. DO NOT EDIT.

package service

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	entity "{{MODULE_NAME}}/internal/shared/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockSystemParameterServiceItf is an autogenerated mock type for the SystemParameterServiceItf type
type MockSystemParameterServiceItf struct {
	mock.Mock
}

type MockSystemParameterServiceItf_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemParameterServiceItf) EXPECT() *MockSystemParameterServiceItf_Expecter {
	return &MockSystemParameterServiceItf_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, mr, data
func (_m *MockSystemParameterServiceItf) Create(ctx context.Context, mr common.MandatoryRequest, data entity.SystemParameter) (*entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, mr, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, entity.SystemParameter) (*entity.SystemParameterRepository, error)); ok {
		return rf(ctx, mr, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, entity.SystemParameter) *entity.SystemParameterRepository); ok {
		r0 = rf(ctx, mr, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, entity.SystemParameter) error); ok {
		r1 = rf(ctx, mr, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterServiceItf_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSystemParameterServiceItf_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - data entity.SystemParameter
func (_e *MockSystemParameterServiceItf_Expecter) Create(ctx interface{}, mr interface{}, data interface{}) *MockSystemParameterServiceItf_Create_Call {
	return &MockSystemParameterServiceItf_Create_Call{Call: _e.mock.On("Create", ctx, mr, data)}
}

func (_c *MockSystemParameterServiceItf_Create_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, data entity.SystemParameter)) *MockSystemParameterServiceItf_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(entity.SystemParameter))
	})
	return _c
}

func (_c *MockSystemParameterServiceItf_Create_Call) Return(_a0 *entity.SystemParameterRepository, _a1 error) *MockSystemParameterServiceItf_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterServiceItf_Create_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, entity.SystemParameter) (*entity.SystemParameterRepository, error)) *MockSystemParameterServiceItf_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function with given fields: ctx, mr, id
func (_m *MockSystemParameterServiceItf) DeleteById(ctx context.Context, mr common.MandatoryRequest, id string) (*entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, mr, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 *entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (*entity.SystemParameterRepository, error)); ok {
		return rf(ctx, mr, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) *entity.SystemParameterRepository); ok {
		r0 = rf(ctx, mr, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterServiceItf_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockSystemParameterServiceItf_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - id string
func (_e *MockSystemParameterServiceItf_Expecter) DeleteById(ctx interface{}, mr interface{}, id interface{}) *MockSystemParameterServiceItf_DeleteById_Call {
	return &MockSystemParameterServiceItf_DeleteById_Call{Call: _e.mock.On("DeleteById", ctx, mr, id)}
}

func (_c *MockSystemParameterServiceItf_DeleteById_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, id string)) *MockSystemParameterServiceItf_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSystemParameterServiceItf_DeleteById_Call) Return(_a0 *entity.SystemParameterRepository, _a1 error) *MockSystemParameterServiceItf_DeleteById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterServiceItf_DeleteById_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (*entity.SystemParameterRepository, error)) *MockSystemParameterServiceItf_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, mr
func (_m *MockSystemParameterServiceItf) FindAll(ctx context.Context, mr common.MandatoryRequest) ([]entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, mr)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest) ([]entity.SystemParameterRepository, error)); ok {
		return rf(ctx, mr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest) []entity.SystemParameterRepository); ok {
		r0 = rf(ctx, mr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest) error); ok {
		r1 = rf(ctx, mr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterServiceItf_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockSystemParameterServiceItf_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
func (_e *MockSystemParameterServiceItf_Expecter) FindAll(ctx interface{}, mr interface{}) *MockSystemParameterServiceItf_FindAll_Call {
	return &MockSystemParameterServiceItf_FindAll_Call{Call: _e.mock.On("FindAll", ctx, mr)}
}

func (_c *MockSystemParameterServiceItf_FindAll_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest)) *MockSystemParameterServiceItf_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockSystemParameterServiceItf_FindAll_Call) Return(_a0 []entity.SystemParameterRepository, _a1 error) *MockSystemParameterServiceItf_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterServiceItf_FindAll_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest) ([]entity.SystemParameterRepository, error)) *MockSystemParameterServiceItf_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPaginated provides a mock function with given fields: ctx, mr, limit, page
func (_m *MockSystemParameterServiceItf) FindAllPaginated(ctx context.Context, mr common.MandatoryRequest, limit int64, page int64) (SystemParameterPage, error) {
	ret := _m.Called(ctx, mr, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginated")
	}

	var r0 SystemParameterPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, int64, int64) (SystemParameterPage, error)); ok {
		return rf(ctx, mr, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, int64, int64) SystemParameterPage); ok {
		r0 = rf(ctx, mr, limit, page)
	} else {
		r0 = ret.Get(0).(SystemParameterPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, int64, int64) error); ok {
		r1 = rf(ctx, mr, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterServiceItf_FindAllPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPaginated'
type MockSystemParameterServiceItf_FindAllPaginated_Call struct {
	*mock.Call
}

// FindAllPaginated is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - limit int64
//   - page int64
func (_e *MockSystemParameterServiceItf_Expecter) FindAllPaginated(ctx interface{}, mr interface{}, limit interface{}, page interface{}) *MockSystemParameterServiceItf_FindAllPaginated_Call {
	return &MockSystemParameterServiceItf_FindAllPaginated_Call{Call: _e.mock.On("FindAllPaginated", ctx, mr, limit, page)}
}

func (_c *MockSystemParameterServiceItf_FindAllPaginated_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, limit int64, page int64)) *MockSystemParameterServiceItf_FindAllPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockSystemParameterServiceItf_FindAllPaginated_Call) Return(_a0 SystemParameterPage, _a1 error) *MockSystemParameterServiceItf_FindAllPaginated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterServiceItf_FindAllPaginated_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, int64, int64) (SystemParameterPage, error)) *MockSystemParameterServiceItf_FindAllPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, mr, id
func (_m *MockSystemParameterServiceItf) FindByID(ctx context.Context, mr common.MandatoryRequest, id string) (*entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, mr, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (*entity.SystemParameterRepository, error)); ok {
		return rf(ctx, mr, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) *entity.SystemParameterRepository); ok {
		r0 = rf(ctx, mr, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterServiceItf_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSystemParameterServiceItf_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - id string
func (_e *MockSystemParameterServiceItf_Expecter) FindByID(ctx interface{}, mr interface{}, id interface{}) *MockSystemParameterServiceItf_FindByID_Call {
	return &MockSystemParameterServiceItf_FindByID_Call{Call: _e.mock.On("FindByID", ctx, mr, id)}
}

func (_c *MockSystemParameterServiceItf_FindByID_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, id string)) *MockSystemParameterServiceItf_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSystemParameterServiceItf_FindByID_Call) Return(_a0 *entity.SystemParameterRepository, _a1 error) *MockSystemParameterServiceItf_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterServiceItf_FindByID_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (*entity.SystemParameterRepository, error)) *MockSystemParameterServiceItf_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByVariable provides a mock function with given fields: ctx, mr, variable
func (_m *MockSystemParameterServiceItf) FindByVariable(ctx context.Context, mr common.MandatoryRequest, variable string) (*entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, mr, variable)

	if len(ret) == 0 {
		panic("no return value specified for FindByVariable")
	}

	var r0 *entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (*entity.SystemParameterRepository, error)); ok {
		return rf(ctx, mr, variable)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) *entity.SystemParameterRepository); ok {
		r0 = rf(ctx, mr, variable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, variable)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterServiceItf_FindByVariable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByVariable'
type MockSystemParameterServiceItf_FindByVariable_Call struct {
	*mock.Call
}

// FindByVariable is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - variable string
func (_e *MockSystemParameterServiceItf_Expecter) FindByVariable(ctx interface{}, mr interface{}, variable interface{}) *MockSystemParameterServiceItf_FindByVariable_Call {
	return &MockSystemParameterServiceItf_FindByVariable_Call{Call: _e.mock.On("FindByVariable", ctx, mr, variable)}
}

func (_c *MockSystemParameterServiceItf_FindByVariable_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, variable string)) *MockSystemParameterServiceItf_FindByVariable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSystemParameterServiceItf_FindByVariable_Call) Return(_a0 *entity.SystemParameterRepository, _a1 error) *MockSystemParameterServiceItf_FindByVariable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterServiceItf_FindByVariable_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (*entity.SystemParameterRepository, error)) *MockSystemParameterServiceItf_FindByVariable_Call {
	_c.Call.Return(run)
	return _c
}

// FindByVariableByCache provides a mock function with given fields: ctx, mr, variable
func (_m *MockSystemParameterServiceItf) FindByVariableByCache(ctx context.Context, mr common.MandatoryRequest, variable string) (entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, mr, variable)

	if len(ret) == 0 {
		panic("no return value specified for FindByVariableByCache")
	}

	var r0 entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (entity.SystemParameterRepository, error)); ok {
		return rf(ctx, mr, variable)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) entity.SystemParameterRepository); ok {
		r0 = rf(ctx, mr, variable)
	} else {
		r0 = ret.Get(0).(entity.SystemParameterRepository)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, variable)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterServiceItf_FindByVariableByCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByVariableByCache'
type MockSystemParameterServiceItf_FindByVariableByCache_Call struct {
	*mock.Call
}

// FindByVariableByCache is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - variable string
func (_e *MockSystemParameterServiceItf_Expecter) FindByVariableByCache(ctx interface{}, mr interface{}, variable interface{}) *MockSystemParameterServiceItf_FindByVariableByCache_Call {
	return &MockSystemParameterServiceItf_FindByVariableByCache_Call{Call: _e.mock.On("FindByVariableByCache", ctx, mr, variable)}
}

func (_c *MockSystemParameterServiceItf_FindByVariableByCache_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, variable string)) *MockSystemParameterServiceItf_FindByVariableByCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSystemParameterServiceItf_FindByVariableByCache_Call) Return(_a0 entity.SystemParameterRepository, _a1 error) *MockSystemParameterServiceItf_FindByVariableByCache_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterServiceItf_FindByVariableByCache_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (entity.SystemParameterRepository, error)) *MockSystemParameterServiceItf_FindByVariableByCache_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function with given fields: ctx, mr, id, data
func (_m *MockSystemParameterServiceItf) UpdateByID(ctx context.Context, mr common.MandatoryRequest, id string, data entity.SystemParameter) (*entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, mr, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 *entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string, entity.SystemParameter) (*entity.SystemParameterRepository, error)); ok {
		return rf(ctx, mr, id, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string, entity.SystemParameter) *entity.SystemParameterRepository); ok {
		r0 = rf(ctx, mr, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string, entity.SystemParameter) error); ok {
		r1 = rf(ctx, mr, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterServiceItf_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockSystemParameterServiceItf_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - id string
//   - data entity.SystemParameter
func (_e *MockSystemParameterServiceItf_Expecter) UpdateByID(ctx interface{}, mr interface{}, id interface{}, data interface{}) *MockSystemParameterServiceItf_UpdateByID_Call {
	return &MockSystemParameterServiceItf_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, mr, id, data)}
}

func (_c *MockSystemParameterServiceItf_UpdateByID_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, id string, data entity.SystemParameter)) *MockSystemParameterServiceItf_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string), args[3].(entity.SystemParameter))
	})
	return _c
}

func (_c *MockSystemParameterServiceItf_UpdateByID_Call) Return(_a0 *entity.SystemParameterRepository, _a1 error) *MockSystemParameterServiceItf_UpdateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterServiceItf_UpdateByID_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string, entity.SystemParameter) (*entity.SystemParameterRepository, error)) *MockSystemParameterServiceItf_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSystemParameterServiceItf creates a new instance of MockSystemParameterServiceItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemParameterServiceItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemParameterServiceItf {
	mock := &MockSystemParameterServiceItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
