// Code generated by mockery v2.43.0. DO NOT EDIT.

package service

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	dto "{{MODULE_NAME}}/internal/shared/dto"

	entity "{{MODULE_NAME}}/internal/shared/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionService is an autogenerated mock type for the SessionService type
type MockSessionService struct {
	mock.Mock
}

type MockSessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionService) EXPECT() *MockSessionService_Expecter {
	return &MockSessionService_Expecter{mock: &_m.Mock}
}

// GetToken provides a mock function with given fields: ctx, mr, supplierCode
func (_m *MockSessionService) GetToken(ctx context.Context, mr common.MandatoryRequest, supplierCode string) (dto.SessionSignatureDto, error) {
	ret := _m.Called(ctx, mr, supplierCode)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 dto.SessionSignatureDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (dto.SessionSignatureDto, error)); ok {
		return rf(ctx, mr, supplierCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) dto.SessionSignatureDto); ok {
		r0 = rf(ctx, mr, supplierCode)
	} else {
		r0 = ret.Get(0).(dto.SessionSignatureDto)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, supplierCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionService_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockSessionService_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - supplierCode string
func (_e *MockSessionService_Expecter) GetToken(ctx interface{}, mr interface{}, supplierCode interface{}) *MockSessionService_GetToken_Call {
	return &MockSessionService_GetToken_Call{Call: _e.mock.On("GetToken", ctx, mr, supplierCode)}
}

func (_c *MockSessionService_GetToken_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, supplierCode string)) *MockSessionService_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSessionService_GetToken_Call) Return(_a0 dto.SessionSignatureDto, _a1 error) *MockSessionService_GetToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionService_GetToken_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (dto.SessionSignatureDto, error)) *MockSessionService_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// SetFreshStateToContext provides a mock function with given fields: ctx, mr, supplierCode
func (_m *MockSessionService) SetFreshStateToContext(ctx context.Context, mr common.MandatoryRequest, supplierCode string) (context.Context, error) {
	ret := _m.Called(ctx, mr, supplierCode)

	if len(ret) == 0 {
		panic("no return value specified for SetFreshStateToContext")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (context.Context, error)); ok {
		return rf(ctx, mr, supplierCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) context.Context); ok {
		r0 = rf(ctx, mr, supplierCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, supplierCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionService_SetFreshStateToContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFreshStateToContext'
type MockSessionService_SetFreshStateToContext_Call struct {
	*mock.Call
}

// SetFreshStateToContext is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - supplierCode string
func (_e *MockSessionService_Expecter) SetFreshStateToContext(ctx interface{}, mr interface{}, supplierCode interface{}) *MockSessionService_SetFreshStateToContext_Call {
	return &MockSessionService_SetFreshStateToContext_Call{Call: _e.mock.On("SetFreshStateToContext", ctx, mr, supplierCode)}
}

func (_c *MockSessionService_SetFreshStateToContext_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, supplierCode string)) *MockSessionService_SetFreshStateToContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSessionService_SetFreshStateToContext_Call) Return(resCtx context.Context, err error) *MockSessionService_SetFreshStateToContext_Call {
	_c.Call.Return(resCtx, err)
	return _c
}

func (_c *MockSessionService_SetFreshStateToContext_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (context.Context, error)) *MockSessionService_SetFreshStateToContext_Call {
	_c.Call.Return(run)
	return _c
}

// SetFreshStateToContextWithCredential provides a mock function with given fields: ctx, mr, credential
func (_m *MockSessionService) SetFreshStateToContextWithCredential(ctx context.Context, mr common.MandatoryRequest, credential entity.CredentialRepository) (context.Context, error) {
	ret := _m.Called(ctx, mr, credential)

	if len(ret) == 0 {
		panic("no return value specified for SetFreshStateToContextWithCredential")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, entity.CredentialRepository) (context.Context, error)); ok {
		return rf(ctx, mr, credential)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, entity.CredentialRepository) context.Context); ok {
		r0 = rf(ctx, mr, credential)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, entity.CredentialRepository) error); ok {
		r1 = rf(ctx, mr, credential)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionService_SetFreshStateToContextWithCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFreshStateToContextWithCredential'
type MockSessionService_SetFreshStateToContextWithCredential_Call struct {
	*mock.Call
}

// SetFreshStateToContextWithCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - credential entity.CredentialRepository
func (_e *MockSessionService_Expecter) SetFreshStateToContextWithCredential(ctx interface{}, mr interface{}, credential interface{}) *MockSessionService_SetFreshStateToContextWithCredential_Call {
	return &MockSessionService_SetFreshStateToContextWithCredential_Call{Call: _e.mock.On("SetFreshStateToContextWithCredential", ctx, mr, credential)}
}

func (_c *MockSessionService_SetFreshStateToContextWithCredential_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, credential entity.CredentialRepository)) *MockSessionService_SetFreshStateToContextWithCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(entity.CredentialRepository))
	})
	return _c
}

func (_c *MockSessionService_SetFreshStateToContextWithCredential_Call) Return(resCtx context.Context, err error) *MockSessionService_SetFreshStateToContextWithCredential_Call {
	_c.Call.Return(resCtx, err)
	return _c
}

func (_c *MockSessionService_SetFreshStateToContextWithCredential_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, entity.CredentialRepository) (context.Context, error)) *MockSessionService_SetFreshStateToContextWithCredential_Call {
	_c.Call.Return(run)
	return _c
}

// SetStateToContextFromCache provides a mock function with given fields: ctx, mr, supplierCode
func (_m *MockSessionService) SetStateToContextFromCache(ctx context.Context, mr common.MandatoryRequest, supplierCode string) (context.Context, error) {
	ret := _m.Called(ctx, mr, supplierCode)

	if len(ret) == 0 {
		panic("no return value specified for SetStateToContextFromCache")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (context.Context, error)); ok {
		return rf(ctx, mr, supplierCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) context.Context); ok {
		r0 = rf(ctx, mr, supplierCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, supplierCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionService_SetStateToContextFromCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStateToContextFromCache'
type MockSessionService_SetStateToContextFromCache_Call struct {
	*mock.Call
}

// SetStateToContextFromCache is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - supplierCode string
func (_e *MockSessionService_Expecter) SetStateToContextFromCache(ctx interface{}, mr interface{}, supplierCode interface{}) *MockSessionService_SetStateToContextFromCache_Call {
	return &MockSessionService_SetStateToContextFromCache_Call{Call: _e.mock.On("SetStateToContextFromCache", ctx, mr, supplierCode)}
}

func (_c *MockSessionService_SetStateToContextFromCache_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, supplierCode string)) *MockSessionService_SetStateToContextFromCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSessionService_SetStateToContextFromCache_Call) Return(resCtx context.Context, err error) *MockSessionService_SetStateToContextFromCache_Call {
	_c.Call.Return(resCtx, err)
	return _c
}

func (_c *MockSessionService_SetStateToContextFromCache_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (context.Context, error)) *MockSessionService_SetStateToContextFromCache_Call {
	_c.Call.Return(run)
	return _c
}

// SetStateToContextFromCacheWithFallback provides a mock function with given fields: ctx, mr, supplierCode
func (_m *MockSessionService) SetStateToContextFromCacheWithFallback(ctx context.Context, mr common.MandatoryRequest, supplierCode string) (context.Context, error) {
	ret := _m.Called(ctx, mr, supplierCode)

	if len(ret) == 0 {
		panic("no return value specified for SetStateToContextFromCacheWithFallback")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) (context.Context, error)); ok {
		return rf(ctx, mr, supplierCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) context.Context); ok {
		r0 = rf(ctx, mr, supplierCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, supplierCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionService_SetStateToContextFromCacheWithFallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStateToContextFromCacheWithFallback'
type MockSessionService_SetStateToContextFromCacheWithFallback_Call struct {
	*mock.Call
}

// SetStateToContextFromCacheWithFallback is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - supplierCode string
func (_e *MockSessionService_Expecter) SetStateToContextFromCacheWithFallback(ctx interface{}, mr interface{}, supplierCode interface{}) *MockSessionService_SetStateToContextFromCacheWithFallback_Call {
	return &MockSessionService_SetStateToContextFromCacheWithFallback_Call{Call: _e.mock.On("SetStateToContextFromCacheWithFallback", ctx, mr, supplierCode)}
}

func (_c *MockSessionService_SetStateToContextFromCacheWithFallback_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, supplierCode string)) *MockSessionService_SetStateToContextFromCacheWithFallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSessionService_SetStateToContextFromCacheWithFallback_Call) Return(resCtx context.Context, err error) *MockSessionService_SetStateToContextFromCacheWithFallback_Call {
	_c.Call.Return(resCtx, err)
	return _c
}

func (_c *MockSessionService_SetStateToContextFromCacheWithFallback_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) (context.Context, error)) *MockSessionService_SetStateToContextFromCacheWithFallback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionService creates a new instance of MockSessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionService {
	mock := &MockSessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
