// Code generated by mockery v2.43.0. DO NOT EDIT.

package service

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	issued "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/request/issued"

	mock "github.com/stretchr/testify/mock"

	responseissued "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/response/issued"
)

// MockIssuedServiceItf is an autogenerated mock type for the IssuedServiceItf type
type MockIssuedServiceItf struct {
	mock.Mock
}

type MockIssuedServiceItf_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIssuedServiceItf) EXPECT() *MockIssuedServiceItf_Expecter {
	return &MockIssuedServiceItf_Expecter{mock: &_m.Mock}
}

// Issued provides a mock function with given fields: ctx, mr, req
func (_m *MockIssuedServiceItf) Issued(ctx context.Context, mr common.MandatoryRequest, req issued.IntegratorIssuedRequest) (responseissued.IssuedResponse, error) {
	ret := _m.Called(ctx, mr, req)

	if len(ret) == 0 {
		panic("no return value specified for Issued")
	}

	var r0 responseissued.IssuedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, issued.IntegratorIssuedRequest) (responseissued.IssuedResponse, error)); ok {
		return rf(ctx, mr, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, issued.IntegratorIssuedRequest) responseissued.IssuedResponse); ok {
		r0 = rf(ctx, mr, req)
	} else {
		r0 = ret.Get(0).(responseissued.IssuedResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, issued.IntegratorIssuedRequest) error); ok {
		r1 = rf(ctx, mr, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssuedServiceItf_Issued_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issued'
type MockIssuedServiceItf_Issued_Call struct {
	*mock.Call
}

// Issued is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - req issued.IntegratorIssuedRequest
func (_e *MockIssuedServiceItf_Expecter) Issued(ctx interface{}, mr interface{}, req interface{}) *MockIssuedServiceItf_Issued_Call {
	return &MockIssuedServiceItf_Issued_Call{Call: _e.mock.On("Issued", ctx, mr, req)}
}

func (_c *MockIssuedServiceItf_Issued_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, req issued.IntegratorIssuedRequest)) *MockIssuedServiceItf_Issued_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(issued.IntegratorIssuedRequest))
	})
	return _c
}

func (_c *MockIssuedServiceItf_Issued_Call) Return(_a0 responseissued.IssuedResponse, _a1 error) *MockIssuedServiceItf_Issued_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssuedServiceItf_Issued_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, issued.IntegratorIssuedRequest) (responseissued.IssuedResponse, error)) *MockIssuedServiceItf_Issued_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIssuedServiceItf creates a new instance of MockIssuedServiceItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssuedServiceItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssuedServiceItf {
	mock := &MockIssuedServiceItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
