// Code generated by mockery v2.43.0. DO NOT EDIT.

package service

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	dto "{{MODULE_NAME}}/internal/shared/dto"

	entity "{{MODULE_NAME}}/internal/shared/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockCurrencyService is an autogenerated mock type for the CurrencyService type
type MockCurrencyService struct {
	mock.Mock
}

type MockCurrencyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCurrencyService) EXPECT() *MockCurrencyService_Expecter {
	return &MockCurrencyService_Expecter{mock: &_m.Mock}
}

// GetCurrencyCodeFromCodeToV1 provides a mock function with given fields: ctx, mr, codeFrom, codeTo
func (_m *MockCurrencyService) GetCurrencyCodeFromCodeToV1(ctx context.Context, mr common.MandatoryRequest, codeFrom string, codeTo string) (entity.CurrencyRepository, error) {
	ret := _m.Called(ctx, mr, codeFrom, codeTo)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyCodeFromCodeToV1")
	}

	var r0 entity.CurrencyRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string, string) (entity.CurrencyRepository, error)); ok {
		return rf(ctx, mr, codeFrom, codeTo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string, string) entity.CurrencyRepository); ok {
		r0 = rf(ctx, mr, codeFrom, codeTo)
	} else {
		r0 = ret.Get(0).(entity.CurrencyRepository)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string, string) error); ok {
		r1 = rf(ctx, mr, codeFrom, codeTo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCurrencyService_GetCurrencyCodeFromCodeToV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrencyCodeFromCodeToV1'
type MockCurrencyService_GetCurrencyCodeFromCodeToV1_Call struct {
	*mock.Call
}

// GetCurrencyCodeFromCodeToV1 is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - codeFrom string
//   - codeTo string
func (_e *MockCurrencyService_Expecter) GetCurrencyCodeFromCodeToV1(ctx interface{}, mr interface{}, codeFrom interface{}, codeTo interface{}) *MockCurrencyService_GetCurrencyCodeFromCodeToV1_Call {
	return &MockCurrencyService_GetCurrencyCodeFromCodeToV1_Call{Call: _e.mock.On("GetCurrencyCodeFromCodeToV1", ctx, mr, codeFrom, codeTo)}
}

func (_c *MockCurrencyService_GetCurrencyCodeFromCodeToV1_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, codeFrom string, codeTo string)) *MockCurrencyService_GetCurrencyCodeFromCodeToV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCurrencyService_GetCurrencyCodeFromCodeToV1_Call) Return(_a0 entity.CurrencyRepository, _a1 error) *MockCurrencyService_GetCurrencyCodeFromCodeToV1_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCurrencyService_GetCurrencyCodeFromCodeToV1_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string, string) (entity.CurrencyRepository, error)) *MockCurrencyService_GetCurrencyCodeFromCodeToV1_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, currencyKafka
func (_m *MockCurrencyService) Upsert(ctx context.Context, currencyKafka dto.CurrencyKafka) error {
	ret := _m.Called(ctx, currencyKafka)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CurrencyKafka) error); ok {
		r0 = rf(ctx, currencyKafka)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCurrencyService_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockCurrencyService_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - currencyKafka dto.CurrencyKafka
func (_e *MockCurrencyService_Expecter) Upsert(ctx interface{}, currencyKafka interface{}) *MockCurrencyService_Upsert_Call {
	return &MockCurrencyService_Upsert_Call{Call: _e.mock.On("Upsert", ctx, currencyKafka)}
}

func (_c *MockCurrencyService_Upsert_Call) Run(run func(ctx context.Context, currencyKafka dto.CurrencyKafka)) *MockCurrencyService_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CurrencyKafka))
	})
	return _c
}

func (_c *MockCurrencyService_Upsert_Call) Return(_a0 error) *MockCurrencyService_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCurrencyService_Upsert_Call) RunAndReturn(run func(context.Context, dto.CurrencyKafka) error) *MockCurrencyService_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCurrencyService creates a new instance of MockCurrencyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCurrencyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCurrencyService {
	mock := &MockCurrencyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
