// Code generated by mockery v2.43.0. DO NOT EDIT.

package service

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	dto "{{MODULE_NAME}}/internal/shared/dto"

	entity "{{MODULE_NAME}}/internal/shared/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockCredentialLogServiceItf is an autogenerated mock type for the CredentialLogServiceItf type
type MockCredentialLogServiceItf struct {
	mock.Mock
}

type MockCredentialLogServiceItf_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialLogServiceItf) EXPECT() *MockCredentialLogServiceItf_Expecter {
	return &MockCredentialLogServiceItf_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, mr, data
func (_m *MockCredentialLogServiceItf) Create(ctx context.Context, mr common.MandatoryRequest, data *entity.CredentialRepository) (*entity.CredentialLogRepository, error) {
	ret := _m.Called(ctx, mr, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.CredentialLogRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, *entity.CredentialRepository) (*entity.CredentialLogRepository, error)); ok {
		return rf(ctx, mr, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, *entity.CredentialRepository) *entity.CredentialLogRepository); ok {
		r0 = rf(ctx, mr, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CredentialLogRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, *entity.CredentialRepository) error); ok {
		r1 = rf(ctx, mr, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialLogServiceItf_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCredentialLogServiceItf_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - data *entity.CredentialRepository
func (_e *MockCredentialLogServiceItf_Expecter) Create(ctx interface{}, mr interface{}, data interface{}) *MockCredentialLogServiceItf_Create_Call {
	return &MockCredentialLogServiceItf_Create_Call{Call: _e.mock.On("Create", ctx, mr, data)}
}

func (_c *MockCredentialLogServiceItf_Create_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, data *entity.CredentialRepository)) *MockCredentialLogServiceItf_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(*entity.CredentialRepository))
	})
	return _c
}

func (_c *MockCredentialLogServiceItf_Create_Call) Return(_a0 *entity.CredentialLogRepository, _a1 error) *MockCredentialLogServiceItf_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialLogServiceItf_Create_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, *entity.CredentialRepository) (*entity.CredentialLogRepository, error)) *MockCredentialLogServiceItf_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, mr, id
func (_m *MockCredentialLogServiceItf) FindByID(ctx context.Context, mr common.MandatoryRequest, id string) ([]dto.CredentialLogResponse, error) {
	ret := _m.Called(ctx, mr, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 []dto.CredentialLogResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) ([]dto.CredentialLogResponse, error)); ok {
		return rf(ctx, mr, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, string) []dto.CredentialLogResponse); ok {
		r0 = rf(ctx, mr, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.CredentialLogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, string) error); ok {
		r1 = rf(ctx, mr, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialLogServiceItf_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCredentialLogServiceItf_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - id string
func (_e *MockCredentialLogServiceItf_Expecter) FindByID(ctx interface{}, mr interface{}, id interface{}) *MockCredentialLogServiceItf_FindByID_Call {
	return &MockCredentialLogServiceItf_FindByID_Call{Call: _e.mock.On("FindByID", ctx, mr, id)}
}

func (_c *MockCredentialLogServiceItf_FindByID_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, id string)) *MockCredentialLogServiceItf_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockCredentialLogServiceItf_FindByID_Call) Return(_a0 []dto.CredentialLogResponse, _a1 error) *MockCredentialLogServiceItf_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialLogServiceItf_FindByID_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, string) ([]dto.CredentialLogResponse, error)) *MockCredentialLogServiceItf_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialLogServiceItf creates a new instance of MockCredentialLogServiceItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialLogServiceItf(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialLogServiceItf {
	mock := &MockCredentialLogServiceItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
