sonar.host.url=http://localhost:9000
# must be unique in a given SonarQube instance
sonar.projectKey={{SERVICE_NAME}}
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set.
sonar.projectName={{SERVICE_NAME}}
sonar.projectVersion=1.0
sonar.login=admin
sonar.password=adminadmin
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set.
sonar.sources=.
sonar.sources.inclusions=internal/**
sonar.exclusions=internal/outbound/**,internal/scheduler/**,cmd/**,**/deps/**, **/mock_**, **/di.go, **/init.go , **/repository/**.go, config/**, docs/**, **/di/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**, /configs/**, **/mock_**, **/repository/**.go, **/module.go, **/di.go
sonar.cpd.exclusions=**/test**.go
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=*.*,conf/**/*.*
sonar.go.coverage.reportPaths=**.out
sonar.go.coverage.dtdVerification=true