package shared

const (
	// - global
	SUCCESS_RESPONSE_CODE                     = "SUCCESS"
	FAILURE_RESPONSE_CODE                     = "FAILURE"
	GET_BAGGAGE_FAILED_RESPONSE_CODE          = "GET_BAGGAGE_FAILED"
	GET_MEAL_FAILED_RESPONSE_CODE             = "GET_MEAL_FAILED"
	GET_SEAT_FAILED_RESPONSE_CODE             = "GET_SEAT_FAILED"
	BAGGAGE_NOT_AVAILABLE_RESPONSE_CODE       = "BAGGAGE_NOT_AVAILABLE"
	MEAL_NOT_AVAILABLE_RESPONSE_CODE          = "MEAL_NOT_AVAILABLE"
	TIMEOUT_ERROR_RESPONSE_CODE               = "TIMEOUT_ERROR"
	BOOKING_FAILED_RESPONSE_CODE              = "BOOKING_FAILED"
	NO_SEAT_RESPONSE_CODE                     = "NO_SEAT"
	MEALS_NOT_AVAILABLE_RESPONSE_CODE         = "MEALS_NOT_AVAILABLE"
	SEAT_NOT_AVAILABLE_RESPONSE_CODE          = "SEAT_NOT_AVAILABLE"
	CANCEL_BOOKING_FAILED_RESPONSE_CODE       = "CANCEL_BOOKING_FAILED"
	SEARCH_FAILED_RESPONSE_CODE               = "SEARCH_FAILED"
	FLIGHT_NOT_FOUND_RESPONSE_CODE            = "FLIGHT_NOT_FOUND"
	INVALID_ROUTE_RESPONSE_CODE               = "INVALID_ROUTE"
	CREDENTIAL_NOT_FOUND_RESPONSE_CODE        = "CREDENTIALS_NOT_FOUND"
	ISSUED_FAILED_RESPONSE_CODE               = "ISSUED_FAILED"
	COMPLETE_REFUND_FAILED_RESPONSE_CODE      = "COMPLETE_REFUND_FAILED"
	SSR_IS_UNAVAILABLE_RESPONSE_CODE          = "SSR_IS_UNAVAILABLE"
	RETRIEVE_BOOKING_FAILED_RESPONSE_CODE     = "RETRIEVE_BOOKING_FAILED"
	REVALIDATE_ITINERARY_FAILED_RESPONSE_CODE = "REVALIDATE_ITINERARY_FAILED"

	// - DB checking
	DATA_IS_EXIST_RESPONSE_CODE       = "DATA_IS_EXIST"
	DATA_NOT_EXIST_RESPONSE_CODE      = "DATA_NOT_EXIST"
	DUPLICATE_DATA_RESPONSE_CODE      = "DUPLICATE_DATA"
	FAILED_UPDATE_DATA_RESPONSE_CODE  = "FAILED_UPDATE_DATA"
	FAILED_DELETED_DATA_RESPONSE_CODE = "FAILED_DELETED_DATA"
	FAILED_INSERT_DATA_RESPONSE_CODE  = "FAILED_INSERT_DATA"
)
