// Code generated by mockery v2.43.0. DO NOT EDIT.

package scheduler

import mock "github.com/stretchr/testify/mock"

// MockSchedulerSystemParameter is an autogenerated mock type for the SchedulerSystemParameter type
type MockSchedulerSystemParameter struct {
	mock.Mock
}

type MockSchedulerSystemParameter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchedulerSystemParameter) EXPECT() *MockSchedulerSystemParameter_Expecter {
	return &MockSchedulerSystemParameter_Expecter{mock: &_m.Mock}
}

// RefreshSystemParameterPredifine provides a mock function with given fields:
func (_m *MockSchedulerSystemParameter) RefreshSystemParameterPredifine() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RefreshSystemParameterPredifine")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSchedulerSystemParameter_RefreshSystemParameterPredifine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshSystemParameterPredifine'
type MockSchedulerSystemParameter_RefreshSystemParameterPredifine_Call struct {
	*mock.Call
}

// RefreshSystemParameterPredifine is a helper method to define mock.On call
func (_e *MockSchedulerSystemParameter_Expecter) RefreshSystemParameterPredifine() *MockSchedulerSystemParameter_RefreshSystemParameterPredifine_Call {
	return &MockSchedulerSystemParameter_RefreshSystemParameterPredifine_Call{Call: _e.mock.On("RefreshSystemParameterPredifine")}
}

func (_c *MockSchedulerSystemParameter_RefreshSystemParameterPredifine_Call) Run(run func()) *MockSchedulerSystemParameter_RefreshSystemParameterPredifine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSchedulerSystemParameter_RefreshSystemParameterPredifine_Call) Return(_a0 error) *MockSchedulerSystemParameter_RefreshSystemParameterPredifine_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSchedulerSystemParameter_RefreshSystemParameterPredifine_Call) RunAndReturn(run func() error) *MockSchedulerSystemParameter_RefreshSystemParameterPredifine_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSchedulerSystemParameter creates a new instance of MockSchedulerSystemParameter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchedulerSystemParameter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchedulerSystemParameter {
	mock := &MockSchedulerSystemParameter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
