// Code generated by mockery v2.43.0. DO NOT EDIT.

package util

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPRequest is an autogenerated mock type for the HTTPRequest type
type MockHTTPRequest struct {
	mock.Mock
}

type MockHTTPRequest_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPRequest) EXPECT() *MockHTTPRequest_Expecter {
	return &MockHTTPRequest_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: _a0, method, url, reqBody, headers
func (_m *MockHTTPRequest) Do(_a0 context.Context, method string, url string, reqBody []byte, headers map[string]string) (*http.Response, error) {
	ret := _m.Called(_a0, method, url, reqBody, headers)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, map[string]string) (*http.Response, error)); ok {
		return rf(_a0, method, url, reqBody, headers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, map[string]string) *http.Response); ok {
		r0 = rf(_a0, method, url, reqBody, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []byte, map[string]string) error); ok {
		r1 = rf(_a0, method, url, reqBody, headers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHTTPRequest_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockHTTPRequest_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - _a0 context.Context
//   - method string
//   - url string
//   - reqBody []byte
//   - headers map[string]string
func (_e *MockHTTPRequest_Expecter) Do(_a0 interface{}, method interface{}, url interface{}, reqBody interface{}, headers interface{}) *MockHTTPRequest_Do_Call {
	return &MockHTTPRequest_Do_Call{Call: _e.mock.On("Do", _a0, method, url, reqBody, headers)}
}

func (_c *MockHTTPRequest_Do_Call) Run(run func(_a0 context.Context, method string, url string, reqBody []byte, headers map[string]string)) *MockHTTPRequest_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte), args[4].(map[string]string))
	})
	return _c
}

func (_c *MockHTTPRequest_Do_Call) Return(_a0 *http.Response, _a1 error) *MockHTTPRequest_Do_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHTTPRequest_Do_Call) RunAndReturn(run func(context.Context, string, string, []byte, map[string]string) (*http.Response, error)) *MockHTTPRequest_Do_Call {
	_c.Call.Return(run)
	return _c
}

// DoWithMetric provides a mock function with given fields: _a0, method, url, reqBody, headers
func (_m *MockHTTPRequest) DoWithMetric(_a0 context.Context, method string, url string, reqBody []byte, headers map[string]string) (*http.Response, error) {
	ret := _m.Called(_a0, method, url, reqBody, headers)

	if len(ret) == 0 {
		panic("no return value specified for DoWithMetric")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, map[string]string) (*http.Response, error)); ok {
		return rf(_a0, method, url, reqBody, headers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, map[string]string) *http.Response); ok {
		r0 = rf(_a0, method, url, reqBody, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []byte, map[string]string) error); ok {
		r1 = rf(_a0, method, url, reqBody, headers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHTTPRequest_DoWithMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithMetric'
type MockHTTPRequest_DoWithMetric_Call struct {
	*mock.Call
}

// DoWithMetric is a helper method to define mock.On call
//   - _a0 context.Context
//   - method string
//   - url string
//   - reqBody []byte
//   - headers map[string]string
func (_e *MockHTTPRequest_Expecter) DoWithMetric(_a0 interface{}, method interface{}, url interface{}, reqBody interface{}, headers interface{}) *MockHTTPRequest_DoWithMetric_Call {
	return &MockHTTPRequest_DoWithMetric_Call{Call: _e.mock.On("DoWithMetric", _a0, method, url, reqBody, headers)}
}

func (_c *MockHTTPRequest_DoWithMetric_Call) Run(run func(_a0 context.Context, method string, url string, reqBody []byte, headers map[string]string)) *MockHTTPRequest_DoWithMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte), args[4].(map[string]string))
	})
	return _c
}

func (_c *MockHTTPRequest_DoWithMetric_Call) Return(_a0 *http.Response, _a1 error) *MockHTTPRequest_DoWithMetric_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHTTPRequest_DoWithMetric_Call) RunAndReturn(run func(context.Context, string, string, []byte, map[string]string) (*http.Response, error)) *MockHTTPRequest_DoWithMetric_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPRequest creates a new instance of MockHTTPRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPRequest {
	mock := &MockHTTPRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
