// Code generated by mockery v2.43.0. DO NOT EDIT.

package scheduler

import mock "github.com/stretchr/testify/mock"

// MockSchedulerCredential is an autogenerated mock type for the SchedulerCredential type
type MockSchedulerCredential struct {
	mock.Mock
}

type MockSchedulerCredential_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSchedulerCredential) EXPECT() *MockSchedulerCredential_Expecter {
	return &MockSchedulerCredential_Expecter{mock: &_m.Mock}
}

// CredentialPredefine provides a mock function with given fields:
func (_m *MockSchedulerCredential) CredentialPredefine() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CredentialPredefine")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSchedulerCredential_CredentialPredefine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CredentialPredefine'
type MockSchedulerCredential_CredentialPredefine_Call struct {
	*mock.Call
}

// CredentialPredefine is a helper method to define mock.On call
func (_e *MockSchedulerCredential_Expecter) CredentialPredefine() *MockSchedulerCredential_CredentialPredefine_Call {
	return &MockSchedulerCredential_CredentialPredefine_Call{Call: _e.mock.On("CredentialPredefine")}
}

func (_c *MockSchedulerCredential_CredentialPredefine_Call) Run(run func()) *MockSchedulerCredential_CredentialPredefine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSchedulerCredential_CredentialPredefine_Call) Return(_a0 error) *MockSchedulerCredential_CredentialPredefine_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSchedulerCredential_CredentialPredefine_Call) RunAndReturn(run func() error) *MockSchedulerCredential_CredentialPredefine_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSchedulerCredential creates a new instance of MockSchedulerCredential. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSchedulerCredential(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSchedulerCredential {
	mock := &MockSchedulerCredential{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
