// Code generated by mockery v2.43.0. DO NOT EDIT.

package bau

import (
	mock "github.com/stretchr/testify/mock"
	modelbau "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/bau"
)

// MockAnalyticsTokenModifier is an autogenerated mock type for the AnalyticsTokenModifier type
type MockAnalyticsTokenModifier struct {
	mock.Mock
}

type MockAnalyticsTokenModifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsTokenModifier) EXPECT() *MockAnalyticsTokenModifier_Expecter {
	return &MockAnalyticsTokenModifier_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields:
func (_m *MockAnalyticsTokenModifier) Complete() {
	_m.Called()
}

// MockAnalyticsTokenModifier_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockAnalyticsTokenModifier_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
func (_e *MockAnalyticsTokenModifier_Expecter) Complete() *MockAnalyticsTokenModifier_Complete_Call {
	return &MockAnalyticsTokenModifier_Complete_Call{Call: _e.mock.On("Complete")}
}

func (_c *MockAnalyticsTokenModifier_Complete_Call) Run(run func()) *MockAnalyticsTokenModifier_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnalyticsTokenModifier_Complete_Call) Return() *MockAnalyticsTokenModifier_Complete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAnalyticsTokenModifier_Complete_Call) RunAndReturn(run func()) *MockAnalyticsTokenModifier_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSegment provides a mock function with given fields: _a0, _a1
func (_m *MockAnalyticsTokenModifier) CreateSegment(_a0 string, _a1 bool) *modelbau.AnalyticSegment {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateSegment")
	}

	var r0 *modelbau.AnalyticSegment
	if rf, ok := ret.Get(0).(func(string, bool) *modelbau.AnalyticSegment); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelbau.AnalyticSegment)
		}
	}

	return r0
}

// MockAnalyticsTokenModifier_CreateSegment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSegment'
type MockAnalyticsTokenModifier_CreateSegment_Call struct {
	*mock.Call
}

// CreateSegment is a helper method to define mock.On call
//   - _a0 string
//   - _a1 bool
func (_e *MockAnalyticsTokenModifier_Expecter) CreateSegment(_a0 interface{}, _a1 interface{}) *MockAnalyticsTokenModifier_CreateSegment_Call {
	return &MockAnalyticsTokenModifier_CreateSegment_Call{Call: _e.mock.On("CreateSegment", _a0, _a1)}
}

func (_c *MockAnalyticsTokenModifier_CreateSegment_Call) Run(run func(_a0 string, _a1 bool)) *MockAnalyticsTokenModifier_CreateSegment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockAnalyticsTokenModifier_CreateSegment_Call) Return(_a0 *modelbau.AnalyticSegment) *MockAnalyticsTokenModifier_CreateSegment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAnalyticsTokenModifier_CreateSegment_Call) RunAndReturn(run func(string, bool) *modelbau.AnalyticSegment) *MockAnalyticsTokenModifier_CreateSegment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnalyticsTokenModifier creates a new instance of MockAnalyticsTokenModifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsTokenModifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsTokenModifier {
	mock := &MockAnalyticsTokenModifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
