// Code generated by mockery v2.43.0. DO NOT EDIT.

package predefine

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockPredefined is an autogenerated mock type for the Predefined type
type MockPredefined struct {
	mock.Mock
}

type MockPredefined_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPredefined) EXPECT() *MockPredefined_Expecter {
	return &MockPredefined_Expecter{mock: &_m.Mock}
}

// FlushData provides a mock function with given fields: ctx
func (_m *MockPredefined) FlushData(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FlushData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPredefined_FlushData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlushData'
type MockPredefined_FlushData_Call struct {
	*mock.Call
}

// FlushData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPredefined_Expecter) FlushData(ctx interface{}) *MockPredefined_FlushData_Call {
	return &MockPredefined_FlushData_Call{Call: _e.mock.On("FlushData", ctx)}
}

func (_c *MockPredefined_FlushData_Call) Run(run func(ctx context.Context)) *MockPredefined_FlushData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPredefined_FlushData_Call) Return(_a0 error) *MockPredefined_FlushData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPredefined_FlushData_Call) RunAndReturn(run func(context.Context) error) *MockPredefined_FlushData_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockPredefined) GetAll(ctx context.Context) map[string]interface{} {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockPredefined_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockPredefined_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPredefined_Expecter) GetAll(ctx interface{}) *MockPredefined_GetAll_Call {
	return &MockPredefined_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockPredefined_GetAll_Call) Run(run func(ctx context.Context)) *MockPredefined_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPredefined_GetAll_Call) Return(_a0 map[string]interface{}) *MockPredefined_GetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPredefined_GetAll_Call) RunAndReturn(run func(context.Context) map[string]interface{}) *MockPredefined_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetDataByID provides a mock function with given fields: ctx, key
func (_m *MockPredefined) GetDataByID(ctx context.Context, key string) (interface{}, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetDataByID")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interface{}, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interface{}); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPredefined_GetDataByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataByID'
type MockPredefined_GetDataByID_Call struct {
	*mock.Call
}

// GetDataByID is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockPredefined_Expecter) GetDataByID(ctx interface{}, key interface{}) *MockPredefined_GetDataByID_Call {
	return &MockPredefined_GetDataByID_Call{Call: _e.mock.On("GetDataByID", ctx, key)}
}

func (_c *MockPredefined_GetDataByID_Call) Run(run func(ctx context.Context, key string)) *MockPredefined_GetDataByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPredefined_GetDataByID_Call) Return(_a0 interface{}, _a1 error) *MockPredefined_GetDataByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPredefined_GetDataByID_Call) RunAndReturn(run func(context.Context, string) (interface{}, error)) *MockPredefined_GetDataByID_Call {
	_c.Call.Return(run)
	return _c
}

// SetData provides a mock function with given fields: ctx, key, data, ttl
func (_m *MockPredefined) SetData(ctx context.Context, key string, data interface{}, ttl time.Duration) error {
	ret := _m.Called(ctx, key, data, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, data, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPredefined_SetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetData'
type MockPredefined_SetData_Call struct {
	*mock.Call
}

// SetData is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data interface{}
//   - ttl time.Duration
func (_e *MockPredefined_Expecter) SetData(ctx interface{}, key interface{}, data interface{}, ttl interface{}) *MockPredefined_SetData_Call {
	return &MockPredefined_SetData_Call{Call: _e.mock.On("SetData", ctx, key, data, ttl)}
}

func (_c *MockPredefined_SetData_Call) Run(run func(ctx context.Context, key string, data interface{}, ttl time.Duration)) *MockPredefined_SetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockPredefined_SetData_Call) Return(_a0 error) *MockPredefined_SetData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPredefined_SetData_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *MockPredefined_SetData_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPredefined creates a new instance of MockPredefined. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPredefined(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPredefined {
	mock := &MockPredefined{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
