package shared

import "errors"

const (
	RESPONSE_CODE_SUCCESS = "SUCCESS"
	RESPONSE_CODE_FAILURE = "FAILURE"

	RESPONSE_CODE_FLIGHT_NOT_FOUND      = "FLIGHT_NOT_FOUND"
	RESPONSE_CODE_FLIGHT_SEARCH_FAILED  = "SEARCH_FAILED"
	RESPONSE_CODE_CANCEL_BOOKING_FAILED = "CANCEL_BOOKING_FAILED"
	RESPONSE_CODE_ISSUED_FAILED         = "ISSUED_FAILED"
	RESPONSE_CODE_BOOKING_FAILED        = "BOOKING_FAILED"
	RESPONSE_CODE_NOT_SEAT              = "NO_SEAT"
	RESPONSE_CODE_INVALID_ROUTE         = "INVALID_ROUTE"
	COMPLETE_REFUND_FAILED              = "COMPLETE_REFUND_FAILED"

	DATA_DUPLICATE        = "DUPLICATE_DATA"
	DATA_NOT_EXIST        = "DATA_NOT_EXIST"
	FAILED_UPDATE_DATA    = "FAILED_UPDATE_DATA"
	FAILED_DELETED_DATA   = "FAILED_DELETED_DATA"
	FAILED_INSERT_DATA    = "FAILED_INSERT_DATA"
	CREDENTIALS_NOT_FOUND = "CREDENTIALS_NOT_FOUND"
)

var (
	ERR_DATA_EXIST                     = errors.New("data already exists")
	ERR_DATA_NOT_EXIST                 = errors.New("data not exist")
	ERR_DUPLICATE_DATA                 = errors.New("duplicate data")
	ERR_FLIGHT_NOT_FOUND               = errors.New(RESPONSE_CODE_FLIGHT_NOT_FOUND)
	ERR_SEARCH_FAILED                  = errors.New(RESPONSE_CODE_FLIGHT_SEARCH_FAILED)
	ERR_BOOKING_FAILED                 = errors.New(RESPONSE_CODE_BOOKING_FAILED)
	ERR_NO_SEAT                        = errors.New(RESPONSE_CODE_NOT_SEAT)
	ERR_INVALID_ROUTE                  = errors.New(RESPONSE_CODE_INVALID_ROUTE)
	ERR_FAILED_INSERT_DATA             = errors.New(FAILED_INSERT_DATA)
	ERR_MISMATCHED_BOOKING_PAX_DATA    = errors.New("booking passengers data is mismatched")
	ERR_INVALID_ISSUED_COMMIT_RESPONSE = errors.New("invalid issued commit response")
)
