// Code generated by mockery v2.43.0. DO NOT EDIT.

package repository

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockCredentialMasterDataInterface is an autogenerated mock type for the CredentialMasterDataInterface type
type MockCredentialMasterDataInterface struct {
	mock.Mock
}

type MockCredentialMasterDataInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialMasterDataInterface) EXPECT() *MockCredentialMasterDataInterface_Expecter {
	return &MockCredentialMasterDataInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data, mr
func (_m *MockCredentialMasterDataInterface) Create(ctx context.Context, data CredentialMasterData, mr common.MandatoryRequest) (*CredentialMasterDataRepository, error) {
	ret := _m.Called(ctx, data, mr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *CredentialMasterDataRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CredentialMasterData, common.MandatoryRequest) (*CredentialMasterDataRepository, error)); ok {
		return rf(ctx, data, mr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CredentialMasterData, common.MandatoryRequest) *CredentialMasterDataRepository); ok {
		r0 = rf(ctx, data, mr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CredentialMasterDataRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, CredentialMasterData, common.MandatoryRequest) error); ok {
		r1 = rf(ctx, data, mr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialMasterDataInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCredentialMasterDataInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data CredentialMasterData
//   - mr common.MandatoryRequest
func (_e *MockCredentialMasterDataInterface_Expecter) Create(ctx interface{}, data interface{}, mr interface{}) *MockCredentialMasterDataInterface_Create_Call {
	return &MockCredentialMasterDataInterface_Create_Call{Call: _e.mock.On("Create", ctx, data, mr)}
}

func (_c *MockCredentialMasterDataInterface_Create_Call) Run(run func(ctx context.Context, data CredentialMasterData, mr common.MandatoryRequest)) *MockCredentialMasterDataInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(CredentialMasterData), args[2].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockCredentialMasterDataInterface_Create_Call) Return(_a0 *CredentialMasterDataRepository, _a1 error) *MockCredentialMasterDataInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialMasterDataInterface_Create_Call) RunAndReturn(run func(context.Context, CredentialMasterData, common.MandatoryRequest) (*CredentialMasterDataRepository, error)) *MockCredentialMasterDataInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function with given fields: ctx, id
func (_m *MockCredentialMasterDataInterface) DeleteByID(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCredentialMasterDataInterface_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockCredentialMasterDataInterface_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockCredentialMasterDataInterface_Expecter) DeleteByID(ctx interface{}, id interface{}) *MockCredentialMasterDataInterface_DeleteByID_Call {
	return &MockCredentialMasterDataInterface_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id)}
}

func (_c *MockCredentialMasterDataInterface_DeleteByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockCredentialMasterDataInterface_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockCredentialMasterDataInterface_DeleteByID_Call) Return(_a0 error) *MockCredentialMasterDataInterface_DeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredentialMasterDataInterface_DeleteByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) error) *MockCredentialMasterDataInterface_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockCredentialMasterDataInterface) FindAll(ctx context.Context) ([]CredentialMasterDataRepository, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []CredentialMasterDataRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]CredentialMasterDataRepository, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []CredentialMasterDataRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]CredentialMasterDataRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialMasterDataInterface_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockCredentialMasterDataInterface_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCredentialMasterDataInterface_Expecter) FindAll(ctx interface{}) *MockCredentialMasterDataInterface_FindAll_Call {
	return &MockCredentialMasterDataInterface_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockCredentialMasterDataInterface_FindAll_Call) Run(run func(ctx context.Context)) *MockCredentialMasterDataInterface_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCredentialMasterDataInterface_FindAll_Call) Return(_a0 []CredentialMasterDataRepository, _a1 error) *MockCredentialMasterDataInterface_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialMasterDataInterface_FindAll_Call) RunAndReturn(run func(context.Context) ([]CredentialMasterDataRepository, error)) *MockCredentialMasterDataInterface_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCredentialMasterDataInterface) FindByID(ctx context.Context, id primitive.ObjectID) (*CredentialMasterDataRepository, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *CredentialMasterDataRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*CredentialMasterDataRepository, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *CredentialMasterDataRepository); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CredentialMasterDataRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialMasterDataInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCredentialMasterDataInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockCredentialMasterDataInterface_Expecter) FindByID(ctx interface{}, id interface{}) *MockCredentialMasterDataInterface_FindByID_Call {
	return &MockCredentialMasterDataInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCredentialMasterDataInterface_FindByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockCredentialMasterDataInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockCredentialMasterDataInterface_FindByID_Call) Return(_a0 *CredentialMasterDataRepository, _a1 error) *MockCredentialMasterDataInterface_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialMasterDataInterface_FindByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) (*CredentialMasterDataRepository, error)) *MockCredentialMasterDataInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByKey provides a mock function with given fields: ctx, key
func (_m *MockCredentialMasterDataInterface) FindByKey(ctx context.Context, key string) (*CredentialMasterDataRepository, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for FindByKey")
	}

	var r0 *CredentialMasterDataRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*CredentialMasterDataRepository, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *CredentialMasterDataRepository); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CredentialMasterDataRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialMasterDataInterface_FindByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByKey'
type MockCredentialMasterDataInterface_FindByKey_Call struct {
	*mock.Call
}

// FindByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCredentialMasterDataInterface_Expecter) FindByKey(ctx interface{}, key interface{}) *MockCredentialMasterDataInterface_FindByKey_Call {
	return &MockCredentialMasterDataInterface_FindByKey_Call{Call: _e.mock.On("FindByKey", ctx, key)}
}

func (_c *MockCredentialMasterDataInterface_FindByKey_Call) Run(run func(ctx context.Context, key string)) *MockCredentialMasterDataInterface_FindByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCredentialMasterDataInterface_FindByKey_Call) Return(_a0 *CredentialMasterDataRepository, _a1 error) *MockCredentialMasterDataInterface_FindByKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialMasterDataInterface_FindByKey_Call) RunAndReturn(run func(context.Context, string) (*CredentialMasterDataRepository, error)) *MockCredentialMasterDataInterface_FindByKey_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function with given fields: ctx, id, data, mr
func (_m *MockCredentialMasterDataInterface) UpdateByID(ctx context.Context, id primitive.ObjectID, data CredentialMasterData, mr common.MandatoryRequest) (*CredentialMasterDataRepository, error) {
	ret := _m.Called(ctx, id, data, mr)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 *CredentialMasterDataRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, CredentialMasterData, common.MandatoryRequest) (*CredentialMasterDataRepository, error)); ok {
		return rf(ctx, id, data, mr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, CredentialMasterData, common.MandatoryRequest) *CredentialMasterDataRepository); ok {
		r0 = rf(ctx, id, data, mr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CredentialMasterDataRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, CredentialMasterData, common.MandatoryRequest) error); ok {
		r1 = rf(ctx, id, data, mr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialMasterDataInterface_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockCredentialMasterDataInterface_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
//   - data CredentialMasterData
//   - mr common.MandatoryRequest
func (_e *MockCredentialMasterDataInterface_Expecter) UpdateByID(ctx interface{}, id interface{}, data interface{}, mr interface{}) *MockCredentialMasterDataInterface_UpdateByID_Call {
	return &MockCredentialMasterDataInterface_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, data, mr)}
}

func (_c *MockCredentialMasterDataInterface_UpdateByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID, data CredentialMasterData, mr common.MandatoryRequest)) *MockCredentialMasterDataInterface_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID), args[2].(CredentialMasterData), args[3].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockCredentialMasterDataInterface_UpdateByID_Call) Return(_a0 *CredentialMasterDataRepository, _a1 error) *MockCredentialMasterDataInterface_UpdateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialMasterDataInterface_UpdateByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID, CredentialMasterData, common.MandatoryRequest) (*CredentialMasterDataRepository, error)) *MockCredentialMasterDataInterface_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialMasterDataInterface creates a new instance of MockCredentialMasterDataInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialMasterDataInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialMasterDataInterface {
	mock := &MockCredentialMasterDataInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
