// Code generated by mockery v2.43.0. DO NOT EDIT.

package repository

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	entity "{{MODULE_NAME}}/internal/shared/entity"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockCredentialLogRepositoryInterface is an autogenerated mock type for the CredentialLogRepositoryInterface type
type MockCredentialLogRepositoryInterface struct {
	mock.Mock
}

type MockCredentialLogRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialLogRepositoryInterface) EXPECT() *MockCredentialLogRepositoryInterface_Expecter {
	return &MockCredentialLogRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data, mr
func (_m *MockCredentialLogRepositoryInterface) Create(ctx context.Context, data entity.CredentialLog, mr common.MandatoryRequest) (*entity.CredentialLogRepository, error) {
	ret := _m.Called(ctx, data, mr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.CredentialLogRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CredentialLog, common.MandatoryRequest) (*entity.CredentialLogRepository, error)); ok {
		return rf(ctx, data, mr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.CredentialLog, common.MandatoryRequest) *entity.CredentialLogRepository); ok {
		r0 = rf(ctx, data, mr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CredentialLogRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.CredentialLog, common.MandatoryRequest) error); ok {
		r1 = rf(ctx, data, mr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialLogRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCredentialLogRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data entity.CredentialLog
//   - mr common.MandatoryRequest
func (_e *MockCredentialLogRepositoryInterface_Expecter) Create(ctx interface{}, data interface{}, mr interface{}) *MockCredentialLogRepositoryInterface_Create_Call {
	return &MockCredentialLogRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, data, mr)}
}

func (_c *MockCredentialLogRepositoryInterface_Create_Call) Run(run func(ctx context.Context, data entity.CredentialLog, mr common.MandatoryRequest)) *MockCredentialLogRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CredentialLog), args[2].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockCredentialLogRepositoryInterface_Create_Call) Return(_a0 *entity.CredentialLogRepository, _a1 error) *MockCredentialLogRepositoryInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialLogRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, entity.CredentialLog, common.MandatoryRequest) (*entity.CredentialLogRepository, error)) *MockCredentialLogRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCredentialLogRepositoryInterface) FindByID(ctx context.Context, id primitive.ObjectID) ([]entity.CredentialLogRepository, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 []entity.CredentialLogRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) ([]entity.CredentialLogRepository, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) []entity.CredentialLogRepository); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CredentialLogRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialLogRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCredentialLogRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockCredentialLogRepositoryInterface_Expecter) FindByID(ctx interface{}, id interface{}) *MockCredentialLogRepositoryInterface_FindByID_Call {
	return &MockCredentialLogRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCredentialLogRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockCredentialLogRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockCredentialLogRepositoryInterface_FindByID_Call) Return(_a0 []entity.CredentialLogRepository, _a1 error) *MockCredentialLogRepositoryInterface_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialLogRepositoryInterface_FindByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) ([]entity.CredentialLogRepository, error)) *MockCredentialLogRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialLogRepositoryInterface creates a new instance of MockCredentialLogRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialLogRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialLogRepositoryInterface {
	mock := &MockCredentialLogRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
