// Code generated by mockery v2.43.0. DO NOT EDIT.

package repository

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	entity "{{MODULE_NAME}}/internal/shared/entity"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockSystemParameterInterface is an autogenerated mock type for the SystemParameterInterface type
type MockSystemParameterInterface struct {
	mock.Mock
}

type MockSystemParameterInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemParameterInterface) EXPECT() *MockSystemParameterInterface_Expecter {
	return &MockSystemParameterInterface_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx
func (_m *MockSystemParameterInterface) Count(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterInterface_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockSystemParameterInterface_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemParameterInterface_Expecter) Count(ctx interface{}) *MockSystemParameterInterface_Count_Call {
	return &MockSystemParameterInterface_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockSystemParameterInterface_Count_Call) Run(run func(ctx context.Context)) *MockSystemParameterInterface_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSystemParameterInterface_Count_Call) Return(_a0 int64, _a1 error) *MockSystemParameterInterface_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterInterface_Count_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockSystemParameterInterface_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, data, mr
func (_m *MockSystemParameterInterface) Create(ctx context.Context, data entity.SystemParameter, mr common.MandatoryRequest) (*entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, data, mr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.SystemParameter, common.MandatoryRequest) (*entity.SystemParameterRepository, error)); ok {
		return rf(ctx, data, mr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.SystemParameter, common.MandatoryRequest) *entity.SystemParameterRepository); ok {
		r0 = rf(ctx, data, mr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.SystemParameter, common.MandatoryRequest) error); ok {
		r1 = rf(ctx, data, mr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSystemParameterInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data entity.SystemParameter
//   - mr common.MandatoryRequest
func (_e *MockSystemParameterInterface_Expecter) Create(ctx interface{}, data interface{}, mr interface{}) *MockSystemParameterInterface_Create_Call {
	return &MockSystemParameterInterface_Create_Call{Call: _e.mock.On("Create", ctx, data, mr)}
}

func (_c *MockSystemParameterInterface_Create_Call) Run(run func(ctx context.Context, data entity.SystemParameter, mr common.MandatoryRequest)) *MockSystemParameterInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.SystemParameter), args[2].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockSystemParameterInterface_Create_Call) Return(_a0 *entity.SystemParameterRepository, _a1 error) *MockSystemParameterInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterInterface_Create_Call) RunAndReturn(run func(context.Context, entity.SystemParameter, common.MandatoryRequest) (*entity.SystemParameterRepository, error)) *MockSystemParameterInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function with given fields: ctx, id, mr
func (_m *MockSystemParameterInterface) DeleteByID(ctx context.Context, id primitive.ObjectID, mr common.MandatoryRequest) error {
	ret := _m.Called(ctx, id, mr)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, common.MandatoryRequest) error); ok {
		r0 = rf(ctx, id, mr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSystemParameterInterface_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockSystemParameterInterface_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
//   - mr common.MandatoryRequest
func (_e *MockSystemParameterInterface_Expecter) DeleteByID(ctx interface{}, id interface{}, mr interface{}) *MockSystemParameterInterface_DeleteByID_Call {
	return &MockSystemParameterInterface_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id, mr)}
}

func (_c *MockSystemParameterInterface_DeleteByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID, mr common.MandatoryRequest)) *MockSystemParameterInterface_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID), args[2].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockSystemParameterInterface_DeleteByID_Call) Return(_a0 error) *MockSystemParameterInterface_DeleteByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemParameterInterface_DeleteByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID, common.MandatoryRequest) error) *MockSystemParameterInterface_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockSystemParameterInterface) FindAll(ctx context.Context) ([]entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.SystemParameterRepository, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.SystemParameterRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterInterface_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockSystemParameterInterface_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSystemParameterInterface_Expecter) FindAll(ctx interface{}) *MockSystemParameterInterface_FindAll_Call {
	return &MockSystemParameterInterface_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockSystemParameterInterface_FindAll_Call) Run(run func(ctx context.Context)) *MockSystemParameterInterface_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSystemParameterInterface_FindAll_Call) Return(_a0 []entity.SystemParameterRepository, _a1 error) *MockSystemParameterInterface_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterInterface_FindAll_Call) RunAndReturn(run func(context.Context) ([]entity.SystemParameterRepository, error)) *MockSystemParameterInterface_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPaginate provides a mock function with given fields: ctx, limit, page
func (_m *MockSystemParameterInterface) FindAllPaginate(ctx context.Context, limit int64, page int64) ([]entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginate")
	}

	var r0 []entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]entity.SystemParameterRepository, error)); ok {
		return rf(ctx, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []entity.SystemParameterRepository); ok {
		r0 = rf(ctx, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterInterface_FindAllPaginate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPaginate'
type MockSystemParameterInterface_FindAllPaginate_Call struct {
	*mock.Call
}

// FindAllPaginate is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int64
//   - page int64
func (_e *MockSystemParameterInterface_Expecter) FindAllPaginate(ctx interface{}, limit interface{}, page interface{}) *MockSystemParameterInterface_FindAllPaginate_Call {
	return &MockSystemParameterInterface_FindAllPaginate_Call{Call: _e.mock.On("FindAllPaginate", ctx, limit, page)}
}

func (_c *MockSystemParameterInterface_FindAllPaginate_Call) Run(run func(ctx context.Context, limit int64, page int64)) *MockSystemParameterInterface_FindAllPaginate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockSystemParameterInterface_FindAllPaginate_Call) Return(_a0 []entity.SystemParameterRepository, _a1 error) *MockSystemParameterInterface_FindAllPaginate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterInterface_FindAllPaginate_Call) RunAndReturn(run func(context.Context, int64, int64) ([]entity.SystemParameterRepository, error)) *MockSystemParameterInterface_FindAllPaginate_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockSystemParameterInterface) FindByID(ctx context.Context, id primitive.ObjectID) (*entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*entity.SystemParameterRepository, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *entity.SystemParameterRepository); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSystemParameterInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockSystemParameterInterface_Expecter) FindByID(ctx interface{}, id interface{}) *MockSystemParameterInterface_FindByID_Call {
	return &MockSystemParameterInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockSystemParameterInterface_FindByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockSystemParameterInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockSystemParameterInterface_FindByID_Call) Return(_a0 *entity.SystemParameterRepository, _a1 error) *MockSystemParameterInterface_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterInterface_FindByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) (*entity.SystemParameterRepository, error)) *MockSystemParameterInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByVariable provides a mock function with given fields: ctx, variable
func (_m *MockSystemParameterInterface) FindByVariable(ctx context.Context, variable string) (*entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, variable)

	if len(ret) == 0 {
		panic("no return value specified for FindByVariable")
	}

	var r0 *entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.SystemParameterRepository, error)); ok {
		return rf(ctx, variable)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.SystemParameterRepository); ok {
		r0 = rf(ctx, variable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, variable)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterInterface_FindByVariable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByVariable'
type MockSystemParameterInterface_FindByVariable_Call struct {
	*mock.Call
}

// FindByVariable is a helper method to define mock.On call
//   - ctx context.Context
//   - variable string
func (_e *MockSystemParameterInterface_Expecter) FindByVariable(ctx interface{}, variable interface{}) *MockSystemParameterInterface_FindByVariable_Call {
	return &MockSystemParameterInterface_FindByVariable_Call{Call: _e.mock.On("FindByVariable", ctx, variable)}
}

func (_c *MockSystemParameterInterface_FindByVariable_Call) Run(run func(ctx context.Context, variable string)) *MockSystemParameterInterface_FindByVariable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSystemParameterInterface_FindByVariable_Call) Return(_a0 *entity.SystemParameterRepository, _a1 error) *MockSystemParameterInterface_FindByVariable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterInterface_FindByVariable_Call) RunAndReturn(run func(context.Context, string) (*entity.SystemParameterRepository, error)) *MockSystemParameterInterface_FindByVariable_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function with given fields: ctx, id, data, mr
func (_m *MockSystemParameterInterface) UpdateByID(ctx context.Context, id primitive.ObjectID, data entity.SystemParameter, mr common.MandatoryRequest) (*entity.SystemParameterRepository, error) {
	ret := _m.Called(ctx, id, data, mr)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 *entity.SystemParameterRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, entity.SystemParameter, common.MandatoryRequest) (*entity.SystemParameterRepository, error)); ok {
		return rf(ctx, id, data, mr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, entity.SystemParameter, common.MandatoryRequest) *entity.SystemParameterRepository); ok {
		r0 = rf(ctx, id, data, mr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.SystemParameterRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, entity.SystemParameter, common.MandatoryRequest) error); ok {
		r1 = rf(ctx, id, data, mr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemParameterInterface_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockSystemParameterInterface_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
//   - data entity.SystemParameter
//   - mr common.MandatoryRequest
func (_e *MockSystemParameterInterface_Expecter) UpdateByID(ctx interface{}, id interface{}, data interface{}, mr interface{}) *MockSystemParameterInterface_UpdateByID_Call {
	return &MockSystemParameterInterface_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, data, mr)}
}

func (_c *MockSystemParameterInterface_UpdateByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID, data entity.SystemParameter, mr common.MandatoryRequest)) *MockSystemParameterInterface_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID), args[2].(entity.SystemParameter), args[3].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockSystemParameterInterface_UpdateByID_Call) Return(_a0 *entity.SystemParameterRepository, _a1 error) *MockSystemParameterInterface_UpdateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemParameterInterface_UpdateByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID, entity.SystemParameter, common.MandatoryRequest) (*entity.SystemParameterRepository, error)) *MockSystemParameterInterface_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSystemParameterInterface creates a new instance of MockSystemParameterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemParameterInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemParameterInterface {
	mock := &MockSystemParameterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
