// Code generated by mockery v2.43.0. DO NOT EDIT.

package repository

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockCacheRepository is an autogenerated mock type for the CacheRepository type
type MockCacheRepository struct {
	mock.Mock
}

type MockCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheRepository) EXPECT() *MockCacheRepository_Expecter {
	return &MockCacheRepository_Expecter{mock: &_m.Mock}
}

// GetWithContext provides a mock function with given fields: ctx, key, data
func (_m *MockCacheRepository) GetWithContext(ctx context.Context, key string, data interface{}) error {
	ret := _m.Called(ctx, key, data)

	if len(ret) == 0 {
		panic("no return value specified for GetWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheRepository_GetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithContext'
type MockCacheRepository_GetWithContext_Call struct {
	*mock.Call
}

// GetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data interface{}
func (_e *MockCacheRepository_Expecter) GetWithContext(ctx interface{}, key interface{}, data interface{}) *MockCacheRepository_GetWithContext_Call {
	return &MockCacheRepository_GetWithContext_Call{Call: _e.mock.On("GetWithContext", ctx, key, data)}
}

func (_c *MockCacheRepository_GetWithContext_Call) Run(run func(ctx context.Context, key string, data interface{})) *MockCacheRepository_GetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockCacheRepository_GetWithContext_Call) Return(_a0 error) *MockCacheRepository_GetWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheRepository_GetWithContext_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockCacheRepository_GetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// IsExistsWithContext provides a mock function with given fields: ctx, key
func (_m *MockCacheRepository) IsExistsWithContext(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for IsExistsWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheRepository_IsExistsWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExistsWithContext'
type MockCacheRepository_IsExistsWithContext_Call struct {
	*mock.Call
}

// IsExistsWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheRepository_Expecter) IsExistsWithContext(ctx interface{}, key interface{}) *MockCacheRepository_IsExistsWithContext_Call {
	return &MockCacheRepository_IsExistsWithContext_Call{Call: _e.mock.On("IsExistsWithContext", ctx, key)}
}

func (_c *MockCacheRepository_IsExistsWithContext_Call) Run(run func(ctx context.Context, key string)) *MockCacheRepository_IsExistsWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheRepository_IsExistsWithContext_Call) Return(_a0 error) *MockCacheRepository_IsExistsWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheRepository_IsExistsWithContext_Call) RunAndReturn(run func(context.Context, string) error) *MockCacheRepository_IsExistsWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveWithContext provides a mock function with given fields: ctx, key
func (_m *MockCacheRepository) RemoveWithContext(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheRepository_RemoveWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveWithContext'
type MockCacheRepository_RemoveWithContext_Call struct {
	*mock.Call
}

// RemoveWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheRepository_Expecter) RemoveWithContext(ctx interface{}, key interface{}) *MockCacheRepository_RemoveWithContext_Call {
	return &MockCacheRepository_RemoveWithContext_Call{Call: _e.mock.On("RemoveWithContext", ctx, key)}
}

func (_c *MockCacheRepository_RemoveWithContext_Call) Run(run func(ctx context.Context, key string)) *MockCacheRepository_RemoveWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheRepository_RemoveWithContext_Call) Return(_a0 error) *MockCacheRepository_RemoveWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheRepository_RemoveWithContext_Call) RunAndReturn(run func(context.Context, string) error) *MockCacheRepository_RemoveWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// SetWithContext provides a mock function with given fields: ctx, key, data
func (_m *MockCacheRepository) SetWithContext(ctx context.Context, key string, data interface{}) error {
	ret := _m.Called(ctx, key, data)

	if len(ret) == 0 {
		panic("no return value specified for SetWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, key, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheRepository_SetWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWithContext'
type MockCacheRepository_SetWithContext_Call struct {
	*mock.Call
}

// SetWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data interface{}
func (_e *MockCacheRepository_Expecter) SetWithContext(ctx interface{}, key interface{}, data interface{}) *MockCacheRepository_SetWithContext_Call {
	return &MockCacheRepository_SetWithContext_Call{Call: _e.mock.On("SetWithContext", ctx, key, data)}
}

func (_c *MockCacheRepository_SetWithContext_Call) Run(run func(ctx context.Context, key string, data interface{})) *MockCacheRepository_SetWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockCacheRepository_SetWithContext_Call) Return(_a0 error) *MockCacheRepository_SetWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheRepository_SetWithContext_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockCacheRepository_SetWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// SetWithExpirationWithContext provides a mock function with given fields: ctx, key, data, ttl
func (_m *MockCacheRepository) SetWithExpirationWithContext(ctx context.Context, key string, data interface{}, ttl time.Duration) error {
	ret := _m.Called(ctx, key, data, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetWithExpirationWithContext")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, data, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheRepository_SetWithExpirationWithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWithExpirationWithContext'
type MockCacheRepository_SetWithExpirationWithContext_Call struct {
	*mock.Call
}

// SetWithExpirationWithContext is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data interface{}
//   - ttl time.Duration
func (_e *MockCacheRepository_Expecter) SetWithExpirationWithContext(ctx interface{}, key interface{}, data interface{}, ttl interface{}) *MockCacheRepository_SetWithExpirationWithContext_Call {
	return &MockCacheRepository_SetWithExpirationWithContext_Call{Call: _e.mock.On("SetWithExpirationWithContext", ctx, key, data, ttl)}
}

func (_c *MockCacheRepository_SetWithExpirationWithContext_Call) Run(run func(ctx context.Context, key string, data interface{}, ttl time.Duration)) *MockCacheRepository_SetWithExpirationWithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCacheRepository_SetWithExpirationWithContext_Call) Return(_a0 error) *MockCacheRepository_SetWithExpirationWithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheRepository_SetWithExpirationWithContext_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *MockCacheRepository_SetWithExpirationWithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheRepository creates a new instance of MockCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheRepository {
	mock := &MockCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
