// Code generated by mockery v2.43.0. DO NOT EDIT.

package repository

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	dto "{{MODULE_NAME}}/internal/shared/dto"

	entity "{{MODULE_NAME}}/internal/shared/entity"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockCredentialRepositoryInterface is an autogenerated mock type for the CredentialRepositoryInterface type
type MockCredentialRepositoryInterface struct {
	mock.Mock
}

type MockCredentialRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialRepositoryInterface) EXPECT() *MockCredentialRepositoryInterface_Expecter {
	return &MockCredentialRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Count provides a mock function with given fields: ctx
func (_m *MockCredentialRepositoryInterface) Count(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialRepositoryInterface_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockCredentialRepositoryInterface_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCredentialRepositoryInterface_Expecter) Count(ctx interface{}) *MockCredentialRepositoryInterface_Count_Call {
	return &MockCredentialRepositoryInterface_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockCredentialRepositoryInterface_Count_Call) Run(run func(ctx context.Context)) *MockCredentialRepositoryInterface_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCredentialRepositoryInterface_Count_Call) Return(_a0 int64, _a1 error) *MockCredentialRepositoryInterface_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialRepositoryInterface_Count_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockCredentialRepositoryInterface_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, data, mr
func (_m *MockCredentialRepositoryInterface) Create(ctx context.Context, data entity.Credential, mr common.MandatoryRequest) (*entity.CredentialRepository, error) {
	ret := _m.Called(ctx, data, mr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Credential, common.MandatoryRequest) (*entity.CredentialRepository, error)); ok {
		return rf(ctx, data, mr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Credential, common.MandatoryRequest) *entity.CredentialRepository); ok {
		r0 = rf(ctx, data, mr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CredentialRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Credential, common.MandatoryRequest) error); ok {
		r1 = rf(ctx, data, mr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCredentialRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data entity.Credential
//   - mr common.MandatoryRequest
func (_e *MockCredentialRepositoryInterface_Expecter) Create(ctx interface{}, data interface{}, mr interface{}) *MockCredentialRepositoryInterface_Create_Call {
	return &MockCredentialRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, data, mr)}
}

func (_c *MockCredentialRepositoryInterface_Create_Call) Run(run func(ctx context.Context, data entity.Credential, mr common.MandatoryRequest)) *MockCredentialRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Credential), args[2].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockCredentialRepositoryInterface_Create_Call) Return(_a0 *entity.CredentialRepository, _a1 error) *MockCredentialRepositoryInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, entity.Credential, common.MandatoryRequest) (*entity.CredentialRepository, error)) *MockCredentialRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function with given fields: ctx, id, mr
func (_m *MockCredentialRepositoryInterface) DeleteByID(ctx context.Context, id primitive.ObjectID, mr common.MandatoryRequest) (*entity.CredentialRepository, error) {
	ret := _m.Called(ctx, id, mr)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 *entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, common.MandatoryRequest) (*entity.CredentialRepository, error)); ok {
		return rf(ctx, id, mr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, common.MandatoryRequest) *entity.CredentialRepository); ok {
		r0 = rf(ctx, id, mr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CredentialRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, common.MandatoryRequest) error); ok {
		r1 = rf(ctx, id, mr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialRepositoryInterface_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockCredentialRepositoryInterface_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
//   - mr common.MandatoryRequest
func (_e *MockCredentialRepositoryInterface_Expecter) DeleteByID(ctx interface{}, id interface{}, mr interface{}) *MockCredentialRepositoryInterface_DeleteByID_Call {
	return &MockCredentialRepositoryInterface_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, id, mr)}
}

func (_c *MockCredentialRepositoryInterface_DeleteByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID, mr common.MandatoryRequest)) *MockCredentialRepositoryInterface_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID), args[2].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockCredentialRepositoryInterface_DeleteByID_Call) Return(_a0 *entity.CredentialRepository, _a1 error) *MockCredentialRepositoryInterface_DeleteByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialRepositoryInterface_DeleteByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID, common.MandatoryRequest) (*entity.CredentialRepository, error)) *MockCredentialRepositoryInterface_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockCredentialRepositoryInterface) FindAll(ctx context.Context) ([]entity.CredentialRepository, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.CredentialRepository, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.CredentialRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CredentialRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialRepositoryInterface_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockCredentialRepositoryInterface_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCredentialRepositoryInterface_Expecter) FindAll(ctx interface{}) *MockCredentialRepositoryInterface_FindAll_Call {
	return &MockCredentialRepositoryInterface_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockCredentialRepositoryInterface_FindAll_Call) Run(run func(ctx context.Context)) *MockCredentialRepositoryInterface_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCredentialRepositoryInterface_FindAll_Call) Return(_a0 []entity.CredentialRepository, _a1 error) *MockCredentialRepositoryInterface_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialRepositoryInterface_FindAll_Call) RunAndReturn(run func(context.Context) ([]entity.CredentialRepository, error)) *MockCredentialRepositoryInterface_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPaginate provides a mock function with given fields: ctx, cf, page, size, sort, sortDirect
func (_m *MockCredentialRepositoryInterface) FindAllPaginate(ctx context.Context, cf dto.CredentialFilter, page int64, size int64, sort string, sortDirect string) ([]entity.CredentialRepository, error) {
	ret := _m.Called(ctx, cf, page, size, sort, sortDirect)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginate")
	}

	var r0 []entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CredentialFilter, int64, int64, string, string) ([]entity.CredentialRepository, error)); ok {
		return rf(ctx, cf, page, size, sort, sortDirect)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CredentialFilter, int64, int64, string, string) []entity.CredentialRepository); ok {
		r0 = rf(ctx, cf, page, size, sort, sortDirect)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CredentialRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CredentialFilter, int64, int64, string, string) error); ok {
		r1 = rf(ctx, cf, page, size, sort, sortDirect)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialRepositoryInterface_FindAllPaginate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPaginate'
type MockCredentialRepositoryInterface_FindAllPaginate_Call struct {
	*mock.Call
}

// FindAllPaginate is a helper method to define mock.On call
//   - ctx context.Context
//   - cf dto.CredentialFilter
//   - page int64
//   - size int64
//   - sort string
//   - sortDirect string
func (_e *MockCredentialRepositoryInterface_Expecter) FindAllPaginate(ctx interface{}, cf interface{}, page interface{}, size interface{}, sort interface{}, sortDirect interface{}) *MockCredentialRepositoryInterface_FindAllPaginate_Call {
	return &MockCredentialRepositoryInterface_FindAllPaginate_Call{Call: _e.mock.On("FindAllPaginate", ctx, cf, page, size, sort, sortDirect)}
}

func (_c *MockCredentialRepositoryInterface_FindAllPaginate_Call) Run(run func(ctx context.Context, cf dto.CredentialFilter, page int64, size int64, sort string, sortDirect string)) *MockCredentialRepositoryInterface_FindAllPaginate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CredentialFilter), args[2].(int64), args[3].(int64), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *MockCredentialRepositoryInterface_FindAllPaginate_Call) Return(_a0 []entity.CredentialRepository, _a1 error) *MockCredentialRepositoryInterface_FindAllPaginate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialRepositoryInterface_FindAllPaginate_Call) RunAndReturn(run func(context.Context, dto.CredentialFilter, int64, int64, string, string) ([]entity.CredentialRepository, error)) *MockCredentialRepositoryInterface_FindAllPaginate_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockCredentialRepositoryInterface) FindByID(ctx context.Context, id primitive.ObjectID) (*entity.CredentialRepository, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) (*entity.CredentialRepository, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *entity.CredentialRepository); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CredentialRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockCredentialRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
func (_e *MockCredentialRepositoryInterface_Expecter) FindByID(ctx interface{}, id interface{}) *MockCredentialRepositoryInterface_FindByID_Call {
	return &MockCredentialRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockCredentialRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID)) *MockCredentialRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID))
	})
	return _c
}

func (_c *MockCredentialRepositoryInterface_FindByID_Call) Return(_a0 *entity.CredentialRepository, _a1 error) *MockCredentialRepositoryInterface_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialRepositoryInterface_FindByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID) (*entity.CredentialRepository, error)) *MockCredentialRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySupplier provides a mock function with given fields: ctx, supplier
func (_m *MockCredentialRepositoryInterface) FindBySupplier(ctx context.Context, supplier string) (*entity.CredentialRepository, error) {
	ret := _m.Called(ctx, supplier)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplier")
	}

	var r0 *entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.CredentialRepository, error)); ok {
		return rf(ctx, supplier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.CredentialRepository); ok {
		r0 = rf(ctx, supplier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CredentialRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, supplier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialRepositoryInterface_FindBySupplier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplier'
type MockCredentialRepositoryInterface_FindBySupplier_Call struct {
	*mock.Call
}

// FindBySupplier is a helper method to define mock.On call
//   - ctx context.Context
//   - supplier string
func (_e *MockCredentialRepositoryInterface_Expecter) FindBySupplier(ctx interface{}, supplier interface{}) *MockCredentialRepositoryInterface_FindBySupplier_Call {
	return &MockCredentialRepositoryInterface_FindBySupplier_Call{Call: _e.mock.On("FindBySupplier", ctx, supplier)}
}

func (_c *MockCredentialRepositoryInterface_FindBySupplier_Call) Run(run func(ctx context.Context, supplier string)) *MockCredentialRepositoryInterface_FindBySupplier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCredentialRepositoryInterface_FindBySupplier_Call) Return(_a0 *entity.CredentialRepository, _a1 error) *MockCredentialRepositoryInterface_FindBySupplier_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialRepositoryInterface_FindBySupplier_Call) RunAndReturn(run func(context.Context, string) (*entity.CredentialRepository, error)) *MockCredentialRepositoryInterface_FindBySupplier_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySupplierAndIsStaging provides a mock function with given fields: ctx, supplier, isStaging
func (_m *MockCredentialRepositoryInterface) FindBySupplierAndIsStaging(ctx context.Context, supplier string, isStaging bool) (*entity.CredentialRepository, error) {
	ret := _m.Called(ctx, supplier, isStaging)

	if len(ret) == 0 {
		panic("no return value specified for FindBySupplierAndIsStaging")
	}

	var r0 *entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (*entity.CredentialRepository, error)); ok {
		return rf(ctx, supplier, isStaging)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) *entity.CredentialRepository); ok {
		r0 = rf(ctx, supplier, isStaging)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CredentialRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, supplier, isStaging)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialRepositoryInterface_FindBySupplierAndIsStaging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySupplierAndIsStaging'
type MockCredentialRepositoryInterface_FindBySupplierAndIsStaging_Call struct {
	*mock.Call
}

// FindBySupplierAndIsStaging is a helper method to define mock.On call
//   - ctx context.Context
//   - supplier string
//   - isStaging bool
func (_e *MockCredentialRepositoryInterface_Expecter) FindBySupplierAndIsStaging(ctx interface{}, supplier interface{}, isStaging interface{}) *MockCredentialRepositoryInterface_FindBySupplierAndIsStaging_Call {
	return &MockCredentialRepositoryInterface_FindBySupplierAndIsStaging_Call{Call: _e.mock.On("FindBySupplierAndIsStaging", ctx, supplier, isStaging)}
}

func (_c *MockCredentialRepositoryInterface_FindBySupplierAndIsStaging_Call) Run(run func(ctx context.Context, supplier string, isStaging bool)) *MockCredentialRepositoryInterface_FindBySupplierAndIsStaging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockCredentialRepositoryInterface_FindBySupplierAndIsStaging_Call) Return(_a0 *entity.CredentialRepository, _a1 error) *MockCredentialRepositoryInterface_FindBySupplierAndIsStaging_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialRepositoryInterface_FindBySupplierAndIsStaging_Call) RunAndReturn(run func(context.Context, string, bool) (*entity.CredentialRepository, error)) *MockCredentialRepositoryInterface_FindBySupplierAndIsStaging_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function with given fields: ctx, id, data, mr
func (_m *MockCredentialRepositoryInterface) UpdateByID(ctx context.Context, id primitive.ObjectID, data entity.Credential, mr common.MandatoryRequest) (*entity.CredentialRepository, error) {
	ret := _m.Called(ctx, id, data, mr)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 *entity.CredentialRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, entity.Credential, common.MandatoryRequest) (*entity.CredentialRepository, error)); ok {
		return rf(ctx, id, data, mr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, entity.Credential, common.MandatoryRequest) *entity.CredentialRepository); ok {
		r0 = rf(ctx, id, data, mr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CredentialRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID, entity.Credential, common.MandatoryRequest) error); ok {
		r1 = rf(ctx, id, data, mr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialRepositoryInterface_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockCredentialRepositoryInterface_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id primitive.ObjectID
//   - data entity.Credential
//   - mr common.MandatoryRequest
func (_e *MockCredentialRepositoryInterface_Expecter) UpdateByID(ctx interface{}, id interface{}, data interface{}, mr interface{}) *MockCredentialRepositoryInterface_UpdateByID_Call {
	return &MockCredentialRepositoryInterface_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, id, data, mr)}
}

func (_c *MockCredentialRepositoryInterface_UpdateByID_Call) Run(run func(ctx context.Context, id primitive.ObjectID, data entity.Credential, mr common.MandatoryRequest)) *MockCredentialRepositoryInterface_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(primitive.ObjectID), args[2].(entity.Credential), args[3].(common.MandatoryRequest))
	})
	return _c
}

func (_c *MockCredentialRepositoryInterface_UpdateByID_Call) Return(_a0 *entity.CredentialRepository, _a1 error) *MockCredentialRepositoryInterface_UpdateByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialRepositoryInterface_UpdateByID_Call) RunAndReturn(run func(context.Context, primitive.ObjectID, entity.Credential, common.MandatoryRequest) (*entity.CredentialRepository, error)) *MockCredentialRepositoryInterface_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialRepositoryInterface creates a new instance of MockCredentialRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialRepositoryInterface {
	mock := &MockCredentialRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
