// Code generated by mockery v2.43.0. DO NOT EDIT.

package repository

import (
	context "context"

	common "github.com/tiket/TIX-FLIGHT-COMMON-MODEL-GO/model/common"

	entity "{{MODULE_NAME}}/internal/shared/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockCurrencyRepositoryInterface is an autogenerated mock type for the CurrencyRepositoryInterface type
type MockCurrencyRepositoryInterface struct {
	mock.Mock
}

type MockCurrencyRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCurrencyRepositoryInterface) EXPECT() *MockCurrencyRepositoryInterface_Expecter {
	return &MockCurrencyRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, mr, data
func (_m *MockCurrencyRepositoryInterface) Create(ctx context.Context, mr common.MandatoryRequest, data entity.Currency) (entity.CurrencyRepository, error) {
	ret := _m.Called(ctx, mr, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entity.CurrencyRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, entity.Currency) (entity.CurrencyRepository, error)); ok {
		return rf(ctx, mr, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.MandatoryRequest, entity.Currency) entity.CurrencyRepository); ok {
		r0 = rf(ctx, mr, data)
	} else {
		r0 = ret.Get(0).(entity.CurrencyRepository)
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.MandatoryRequest, entity.Currency) error); ok {
		r1 = rf(ctx, mr, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCurrencyRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCurrencyRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - mr common.MandatoryRequest
//   - data entity.Currency
func (_e *MockCurrencyRepositoryInterface_Expecter) Create(ctx interface{}, mr interface{}, data interface{}) *MockCurrencyRepositoryInterface_Create_Call {
	return &MockCurrencyRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, mr, data)}
}

func (_c *MockCurrencyRepositoryInterface_Create_Call) Run(run func(ctx context.Context, mr common.MandatoryRequest, data entity.Currency)) *MockCurrencyRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.MandatoryRequest), args[2].(entity.Currency))
	})
	return _c
}

func (_c *MockCurrencyRepositoryInterface_Create_Call) Return(_a0 entity.CurrencyRepository, _a1 error) *MockCurrencyRepositoryInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCurrencyRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, common.MandatoryRequest, entity.Currency) (entity.CurrencyRepository, error)) *MockCurrencyRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockCurrencyRepositoryInterface) FindAll(ctx context.Context) ([]entity.CurrencyRepository, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []entity.CurrencyRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.CurrencyRepository, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.CurrencyRepository); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CurrencyRepository)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCurrencyRepositoryInterface_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockCurrencyRepositoryInterface_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCurrencyRepositoryInterface_Expecter) FindAll(ctx interface{}) *MockCurrencyRepositoryInterface_FindAll_Call {
	return &MockCurrencyRepositoryInterface_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockCurrencyRepositoryInterface_FindAll_Call) Run(run func(ctx context.Context)) *MockCurrencyRepositoryInterface_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCurrencyRepositoryInterface_FindAll_Call) Return(_a0 []entity.CurrencyRepository, _a1 error) *MockCurrencyRepositoryInterface_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCurrencyRepositoryInterface_FindAll_Call) RunAndReturn(run func(context.Context) ([]entity.CurrencyRepository, error)) *MockCurrencyRepositoryInterface_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCodeFrom provides a mock function with given fields: ctx, codeFrom
func (_m *MockCurrencyRepositoryInterface) FindByCodeFrom(ctx context.Context, codeFrom string) (entity.CurrencyRepository, error) {
	ret := _m.Called(ctx, codeFrom)

	if len(ret) == 0 {
		panic("no return value specified for FindByCodeFrom")
	}

	var r0 entity.CurrencyRepository
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.CurrencyRepository, error)); ok {
		return rf(ctx, codeFrom)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.CurrencyRepository); ok {
		r0 = rf(ctx, codeFrom)
	} else {
		r0 = ret.Get(0).(entity.CurrencyRepository)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, codeFrom)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCurrencyRepositoryInterface_FindByCodeFrom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCodeFrom'
type MockCurrencyRepositoryInterface_FindByCodeFrom_Call struct {
	*mock.Call
}

// FindByCodeFrom is a helper method to define mock.On call
//   - ctx context.Context
//   - codeFrom string
func (_e *MockCurrencyRepositoryInterface_Expecter) FindByCodeFrom(ctx interface{}, codeFrom interface{}) *MockCurrencyRepositoryInterface_FindByCodeFrom_Call {
	return &MockCurrencyRepositoryInterface_FindByCodeFrom_Call{Call: _e.mock.On("FindByCodeFrom", ctx, codeFrom)}
}

func (_c *MockCurrencyRepositoryInterface_FindByCodeFrom_Call) Run(run func(ctx context.Context, codeFrom string)) *MockCurrencyRepositoryInterface_FindByCodeFrom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCurrencyRepositoryInterface_FindByCodeFrom_Call) Return(_a0 entity.CurrencyRepository, _a1 error) *MockCurrencyRepositoryInterface_FindByCodeFrom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCurrencyRepositoryInterface_FindByCodeFrom_Call) RunAndReturn(run func(context.Context, string) (entity.CurrencyRepository, error)) *MockCurrencyRepositoryInterface_FindByCodeFrom_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByID provides a mock function with given fields: ctx, currency
func (_m *MockCurrencyRepositoryInterface) UpdateByID(ctx context.Context, currency entity.CurrencyRepository) error {
	ret := _m.Called(ctx, currency)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CurrencyRepository) error); ok {
		r0 = rf(ctx, currency)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCurrencyRepositoryInterface_UpdateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByID'
type MockCurrencyRepositoryInterface_UpdateByID_Call struct {
	*mock.Call
}

// UpdateByID is a helper method to define mock.On call
//   - ctx context.Context
//   - currency entity.CurrencyRepository
func (_e *MockCurrencyRepositoryInterface_Expecter) UpdateByID(ctx interface{}, currency interface{}) *MockCurrencyRepositoryInterface_UpdateByID_Call {
	return &MockCurrencyRepositoryInterface_UpdateByID_Call{Call: _e.mock.On("UpdateByID", ctx, currency)}
}

func (_c *MockCurrencyRepositoryInterface_UpdateByID_Call) Run(run func(ctx context.Context, currency entity.CurrencyRepository)) *MockCurrencyRepositoryInterface_UpdateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.CurrencyRepository))
	})
	return _c
}

func (_c *MockCurrencyRepositoryInterface_UpdateByID_Call) Return(_a0 error) *MockCurrencyRepositoryInterface_UpdateByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCurrencyRepositoryInterface_UpdateByID_Call) RunAndReturn(run func(context.Context, entity.CurrencyRepository) error) *MockCurrencyRepositoryInterface_UpdateByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCurrencyRepositoryInterface creates a new instance of MockCurrencyRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCurrencyRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCurrencyRepositoryInterface {
	mock := &MockCurrencyRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
